### ISSUE TITLE
[FEEDSTOCK REQUEST] tiktoken

### ISSUE THREAD

**Issue by lehrig** [open-ce/open-ce#1010]
**Describe the package you'd like added**
Install tiktoken via conda
https://github.com/openai/tiktoken

**Describe how this package fits in with the project**
tiktoken is a fast BPE tokeniser for use with OpenAI's models.

**Additional context**
submitted on behalf of a banking client in EMEA

**Comment by alexlang74** [comment]
Delivered https://github.com/open-ce/open-ce/releases/tag/open-ce-v1.11.0
