### ISSUE TITLE
[REQUEST] Update jax/jaxlib to >=0.4.23

### ISSUE THREAD

**Issue by amccaugh** [open-ce/open-ce#1058]
Would it be possible to build one of the more recent `jax` versions and/or against CUDA 12? I so far have two issues: (1) I occasionally get segfaults that I suspect are due to CUDA 11.8, and (2) there are a few functions implemented within the last few versions that would be very nice to have.  It appears that up to jax 0.4.23 supports for CUDA 12.2, and contains a lot of the changes since the current jax version in OpenCE (0.4.7 currently).  jax >= 0.4.24 requires CUDA 12.3, which it doesn't seem the latest releases of OpenCE are targeting, but I'm not sure if that's just what the jax devs are willing to maintain or an actual dependency of the jax code.

**Comment by cdeepali** [comment]
jax and jaxlib v0,.4.23 will come in OpenCE v1.11.

**Comment by cdeepali** [comment]
jax and jaxlib v0.4.23 is supplied for x86 CPU/CUDA and ppc64le cpu variants is supplied in OpenCE v1.11 - https://github.com/open-ce/open-ce/releases/tag/open-ce-v1.11.0

CUDA package for ppc64le has some issue and will come in 1.11.x.
