### ISSUE TITLE
[FEEDSTOCK REQUEST] unstructured_inference

### ISSUE THREAD

**Issue by lehrig** [open-ce/open-ce#1063]
**Describe the package you'd like added**
"unstructured_inference" "contains hosted model inference code for layout parsing models.", e.g., for parsing PDFs.

https://github.com/Unstructured-IO/unstructured-inference

**Describe how this package fits in with the project**
In GenAI, documents are often parsed, e.g., in RAG kind of workflows.

**Additional context**

- Requires https://github.com/open-ce/open-ce/issues/1062
- Required by IBM demos: https://github.com/IBM/dsce-sample-apps/blob/main/ask-my-data/requirements.txt

**Comment by rolweber** [comment]
This looks like a pure Python package that can easily be installed from PyPI.
https://pypi.org/project/unstructured-inference/#files

**Comment by cdeepali** [comment]
Can this be closed then?
