### ISSUE TITLE
sentence-transformers for ppc64le

### ISSUE THREAD

**Issue by anjiltech** [open-ce/open-ce#1065]
**Describe the package you'd like added**
Installing **sentence-transformer**  framework on Power fails which is required for the text embedding models.
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

**Describe how this package fits in with the project**
Text embedding models from sentence transformers is used for generating embeddings in  the RAG applications. 

**Additional context**
**all-MiniLM-L6-v2** model used for text embeddings has dependency on **sentence-transformers**
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

Installing  sentence-transformers with conda from conda-forge on Power10 system fails as below:

_# conda install -c conda-forge sentence-transformers_ 
Collecting package metadata (current_repodata.json): done 
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve. 
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source. Collecting package metadata (repodata.json): done Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve. Solving environment: / 

Use of mamba resolver (Instead of the default conda resolver) fails fast with errors showing dependencies on the torch cuda libraries.

Tried installing the sentence-transformers from source and it worked.

Installing from source:
_git clone https://github.com/UKPLab/sentence-transformers.git_
_pip install ._

Having support for sentence-tranformers on ppc64le to work with pytorch-cpu will help deploying text embedding models on Power.

**Comment by rolweber** [comment]
`sentence-transformers` on PyPI is a pure Python package that can be installed on any platform.
https://pypi.org/project/sentence-transformers/#files

Use `pip install sentence-transformers`.

**Comment by cdeepali** [comment]
Closing this based on @rolweber response.
