### ISSUE TITLE
fastapi and langsmith test failure

### ISSUE THREAD

**Issue by Aman-Surkar** [open-ce/open-ce#1193]
While building packages like langsmith, langchain-text-splitters and fastapi, they failed to get built as python version 3.12.4 was causing error with pydantic. Degrading the python to 3.12.3 works and the packages are built successfully.
Error seen:
```
  File "pydantic/main.py", line 286, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 808, in pydantic.main.BaseModel.__try_update_forward_refs__
  File "pydantic/typing.py", line 554, in pydantic.typing.update_model_forward_refs
    return super().__new__(cls)
  File "pydantic/typing.py", line 520, in pydantic.typing.update_field_forward_refs
    class _LiteralSpecialForm(_SpecialForm, _root=True):
  File "pydantic/typing.py", line 66, in pydantic.typing.evaluate_forwardref
    'Union',
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by rolweber** [comment]
What version of pydantic are you using? Looks to me like they fixed problems with Python 3.12 in 1.10.17.
https://docs.pydantic.dev/1.10/changelog/
https://github.com/pydantic/pydantic/issues/9607
https://github.com/pydantic/pydantic/issues/9622

**Comment by Aman-Surkar** [comment]
During the build it pulls `pydantic: 1.10.12-py312h5eee18b_1` and also `pydantic 1.10.17` isn't there in default Anaconda channel.

**Comment by rolweber** [comment]
So it would be an option to build pydantic 1.10.17 in Open CE.

**Comment by cdeepali** [comment]
Fixed by pinning Python in langsmith and fastapi feedstocks https://github.com/open-ce/open-ce/pull/1186/files
