### ISSUE TITLE
Add a driver level check for CUDA11 capable driver before build image creation

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/open-ce#120]
If you build the CUDA11 enabled build image on a system with a CUDA 10.2 driver, you will get a fail similar to

```
oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:339: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=11.0 --pid=57462 /var/lib/docker/overlay2/5a4053aec722d91c7e9849b46b472bb7faf93c565e1b91d6f1b0e3eac7f44df6/merged]\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 11.0\\n\""
```

Which is a bit unclear. Let's check the system before doing the docker image build and output a more legible warning about needing an updated CUDA11 capable driver.

We can use:
```
nvidia-smi --query-gpu=driver_version --format=csv
```
and reference https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility

related to but distinct from: https://github.com/open-ce/open-ce/issues/88
Will be affected by the implementation of: https://github.com/open-ce/open-ce/issues/89
This check will need to look for a driver compatible with the latest CUDA version specified

**Comment by bnemanich** [comment]
@dllehr81 was this already completed in a separate issue?
