### ISSUE TITLE
[FEEDSTOCK REQUEST] lightgbm [cpu/cuda]

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/open-ce#124]
**Describe the package you'd like added**
Add a recipe for LightGBM for cpu and cuda variants.

**Describe how this package fits in with the project**
LightGBM is a popular machine learning framework and would compliment XGBoost

**Additional context**
LightGBM added CUDA support with: https://github.com/microsoft/LightGBM/commit/f7ad945717d90a47f68dcac78ebc508a1fe00c40

The CI job was just set up with CUDA11:
https://github.com/microsoft/LightGBM/commit/12e220b79d459396ce74f60f260786ad67a8fbb9

**Comment by bnemanich** [comment]
This was closed by open-ce/LightGBM-feedstock#1
