### ISSUE TITLE
Create documentation for conda environment file

### ISSUE THREAD

**Issue by npanpaliya** [open-ce/open-ce#150]
Update documentation of build_env.py to describe conda environment files being generated. This will be further used by build_image.py to create a runtime docker image with Open-CE packages installed in it.

**Comment by dncliss** [comment]
@npanpaliya  -- There's no description above, but I think you might be intending this as what we already have as issue #51   ... or did you have something different in mind?

**Comment by dncliss** [comment]
I see I had not originally put you on the reviewers on the associated PR, so I have added you.

**Comment by npanpaliya** [comment]
Thanks @dncliss . This task is different than the one you're working. I've updated the description of the task now. Actually I've also started working on this.

The one you're documenting is about Open-CE environment files for various frameworks which is an input to build_env.py.
