### ISSUE TITLE
[BUG] Add command line argument validation in build scripts

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#151]
The command line arguments for build scripts are currently not validated. So I think it would be good if we add some validation there .

I observed the following non-intuitive error with incorrect arguments:
```
./open-ce/open-ce/build_env.py ./open-ce/envs/spacy-env.yaml --python_versions cuda
***** Error in /home/builder/open-ce/envs/spacy-env.yaml:
  invalid literal for int() with base 10: 'cuda'
Error creating Build Tree
```

**Comment by alexlang74** [comment]
No intent to fix right now
