### ISSUE TITLE
Unified Entrypoint for Open-CE

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#161]
**Is your feature request related to a problem? Please describe.**
We have a lot of different executable scripts, and it could be confusing for a new user

**Describe the solution you'd like**
It would be good to create a primary executable with flags for functions. 

It could work similar to `git`. And it would give users a single entry point, and allow them to use `-h` there and get all the information they need, without the need to know which scripts are executable, and which are libraries.

For example:
```
$> open-ce -h
      open-ce build_env [Options]
      open-ce build_feedstock [Options]
      open-ce validate_config [Options]
      ...
```

A normal build could look something like:
```
$> open-ce build_env open-ce/envs/open-ce-env.yaml --python_vers 3.7 --build_types cpu
```

I think the single access point and centralized help are the biggest benefits of going this way.
It shouldn't add much work other than maintaining the wrapper. We've already standardized our arg parsing.

We might also want to eventually make this a package, and if we do, we will want normal entry point for a user as opposed to some scripts that end in `.py`

**Comment by bnemanich** [comment]
I think we can probably clean things up a little more by having more generic top level commands like `open-ce build`, `open-ce test` and `open-ce verify`. They can work on either feedstocks or environment files based on the arguments passed to the tool.

We can also think about whether the name of the tool should be `open-ce` or something else.
