### ISSUE TITLE
Upgrade TensorFlow to version 2.4

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#166]
Upgrade TF to version 2.4. This includes upgrading the rest of the TF ecosystem to the appropriate versions as well. This should also involve tagging the last commit of each upgraded repository with the appropriate version. For example, the last commit of TensorFlow 2.3.1 should be tagged as v2.3.1.

**Comment by npanpaliya** [comment]
https://github.com/open-ce/tensorflow-serving-feedstock/pull/13
