### ISSUE TITLE
remove typing as a dependency as it is part of Python

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#169]
`typing` module is part of Python package from python versions 3.5 and higher. So we can remove it from the dependencies.

**Comment by jayfurmanek** [comment]
We also need to remove typing as a dependency from:
 - pytorch
 - tokenizers
 - tensorrt

**Comment by jayfurmanek** [comment]
pin to be removed in: https://github.com/open-ce/open-ce/pull/162

**Comment by npanpaliya** [comment]
https://github.com/open-ce/tensorrt-feedstock/pull/11
