### ISSUE TITLE
[REQUEST] Add Ray/Tune framework to Open-CE

### ISSUE THREAD

**Issue by dustinvanstee** [open-ce/open-ce#172]
Would it be possible to add Ray/Tune packages to Open-CE specifically ppc64le?  From time/time I use this library and it used to be available via WML-CE.    I saw right now that the Ray/Tune site only seems to host x86 binaries -> https://docs.ray.io/en/master/installation.html

**Comment by cruyffturn** [comment]
@jayfurmanek In the [documentation of Ray](https://docs.ray.io/en/latest/serialization.html?highlight=pyarrow#overview), it's stated that:

> Ray has decided to use a customed Pickle protocol version 5 backport to replace the original PyArrow serializer. This gets rid of several previous limitations (e.g. cannot serialize recursive objects).

Does it imply that Ray stopped using pyarrow altogether?

**Comment by alexlang74** [comment]
Ray is added in OpenCE 1.6
