### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#173]
Hi, 

I was trying to install open-ce on IBM Power9 system but failed. Could someone give me some advice, please?

Attempting to finalize metadata for onnx
INFO:conda_build.metadata:Attempting to finalize metadata for onnx
INFO conda_build.metadata:finalize_outputs_pass(708): Attempting to finalize metadata for onnx
Error: Failed to render jinja template in /opt/apps/open-ce-v1.0/onnx-feedstock/recipe/meta.yaml:
'typing_extensions' is undefined

**Comment by jayfurmanek** [comment]
Hi @superdavidxp 
Sorry for this. We're working on the next release and updating the recipes We merged in the latest ONNX recipe thinking it was ok, but it does have a new dependency - we not merged in the corresponding updates to the central conda_build_config.yaml file yet.

I'd recommend building the stable release (1.0.1)

**Comment by jayfurmanek** [comment]
We've reverted the ONNX update (it will be pushed back in once a few others updates are ready.
Closing this for now, if the problem persists please reopen.
