### ISSUE TITLE
[BUG] CDTs package building is broken (packages updated on the COS side)

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/open-ce#174]
**Describe the bug**
CentOS updated some packages in the 7 stream that we use to build the CDTs. 

**To Reproduce**
Build bazel or any of the packages that need the CDTs built

**Expected behavior**
The builds work!

**Execution Logs**
```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <http://mirror.centos.org/altarch/7/os/ppc64le/Packages/tzdata-java-2019c-1.el7.noarch.rpm>
Elapsed: 00:00.113178

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(87): Error: HTTP 404 NOT FOUND for url <http://mirror.centos.org/altarch/7/os/ppc64le/Packages/tzdata-java-2019c-1.el7.noarch.rpm>
Elapsed: 00:00.113178
```

**System (please complete the following information):**
Will happen on all, but found on
 - OS: RH8
 - Architecture: x86

**Additional context**
We should update the CDT recipes to pull from stable sources (not the `7` or `7.9` directories)

This will require a fix to 1.0.1

**Comment by jayfurmanek** [comment]
we want tzdata to pull: http://mirror.centos.org/altarch/7.8.2003/os/ppc64le/Packages/tzdata-2019c-1.el7.noarch.rpm
instead of whatever is in:
http://mirror.centos.org/altarch/7/os/ppc64le/Packages/

same for x86.
The versioned dir should'nt change.

**Comment by jayfurmanek** [comment]
This broke again.

**Comment by jayfurmanek** [comment]
https://github.com/open-ce/cdts-feedstock/pull/7

**Comment by bnemanich** [comment]
@jayfurmanek can this be closed now?

**Comment by jayfurmanek** [comment]
Yuppers
