### ISSUE TITLE
[QUESTION] install "pytorch-env.yaml"

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#177]
Dear all,

I have tried to install "pytorch-env.yaml" on IBM Power9, however, there are some error I can not fix. Could someone give me some advice please?

Thank you in advance,

//////////////////////////////////////////
 
  File "/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBLAS=OpenBLAS', '-DBUILD_CUSTOM_PROTOBUF=OFF', '-DBUILD_PREFIX=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_build_env', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Unix Makefiles', '-DCMAKE_INSTALL_PREFIX=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/work/torch', '-DCMAKE_PREFIX_PATH=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/;/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol', '-DNUMPY_INCLUDE_DIR=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python', '-DPYTHON_INCLUDE_DIR=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/python3.6m', '-DPYTHON_LIBRARY=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libpython3.6m.a', '-DTORCH_BUILD_VERSION=1.6.0a0+445c276', '-DUSE_CUDA=0', '-DUSE_CUDNN=0', '-DUSE_FBGEMM=0', '-DUSE_LEVELDB=1', '-DUSE_LMDB=1', '-DUSE_MKLDNN=0', '-DUSE_NNPACK=0', '-DUSE_NUMPY=True', '-DUSE_OPENMP=1', '-DUSE_PYTORCH_QNNPACK=0', '-DUSE_QNNPACK=0', '-DUSE_SYSTEM_NCCL=1', '-DUSE_TENSORRT=0', '-DUSE_XNNPACK=0', '/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/work']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/apps/open-ce-v1.0.1/open-ce/open-ce/build_feedstock.py", line 186, in build_feedstock
    config=config, variants=variant)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 2132, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605293700027/work/conda_build.sh']' returned non-zero exit status 1.
Failure building recipe: pytorch-base
Unable to build recipe: pytorch-feedstock

**Comment by bnemanich** [comment]
Hi,

There isn't enough information in the log snippet to see what the problem is. Could you please post more of the output?

Also, are you building using the `--docker_build` option? If not, please give that a try if you have docker installed on your system.

**Comment by superdavidxp** [comment]
Hi,

Thank you for your help, I have updated with more log message, please guide me what should I do next.

//////////////////////////////////////////

+ [[ cpu == \c\p\u ]]
+ export USE_CUDA=0
+ USE_CUDA=0
+ export USE_CUDNN=0
+ USE_CUDNN=0
+ export USE_TENSORRT=0
+ USE_TENSORRT=0
+ export BLAS=OpenBLAS
+ BLAS=OpenBLAS
+ export USE_FBGEMM=0
+ USE_FBGEMM=0
+ export USE_SYSTEM_NCCL=1
+ USE_SYSTEM_NCCL=1
+ export USE_MKLDNN=0
+ USE_MKLDNN=0
+ export USE_NNPACK=0
+ USE_NNPACK=0
+ export USE_QNNPACK=0
+ USE_QNNPACK=0
+ export USE_XNNPACK=0
+ USE_XNNPACK=0
+ export USE_PYTORCH_QNNPACK=0
+ USE_PYTORCH_QNNPACK=0
+ export TH_BINARY_BUILD=1
+ TH_BINARY_BUILD=1
+ export USE_LMDB=1
+ USE_LMDB=1
+ export USE_LEVELDB=1
+ USE_LEVELDB=1
+ export USE_OPENMP=1
+ USE_OPENMP=1
+ export BUILD_CUSTOM_PROTOBUF=OFF
+ BUILD_CUSTOM_PROTOBUF=OFF
+ export 'CMAKE_PREFIX_PATH=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/;/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol'
+ CMAKE_PREFIX_PATH='/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/;/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol'
+ [[ 0 == 1 ]]
++ uname -p
+ ARCH=ppc64le
+ cd third_party/onnx-tensorrt
+ git checkout 84b5be1d6fc03564f2c0dba85a2ee75bad242c2e
Previous HEAD position was c153211... Add check that network is build with full dims set
HEAD is now at 84b5be1... TensorRT 7.0 open source release
M	third_party/onnx
+ cd ../..
+ [[ ppc64le == \x\8\6\_\6\4 ]]
+ MAX_JOBS=160
+ python setup.py install
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
Building wheel torch-1.6.0a0+445c276
-- Building version 1.6.0a0+445c276
cmake -GNinja -DBLAS=OpenBLAS -DBUILD_CUSTOM_PROTOBUF=OFF -DBUILD_PREFIX=$BUILD_PREFIX -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR=Unix Makefiles -DCMAKE_INSTALL_PREFIX=$SRC_DIR/torch -DCMAKE_PREFIX_PATH=$BUILD_PREFIX/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/;$PREFIX -DNUMPY_INCLUDE_DIR=$PREFIX/lib/python3.6/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=$PREFIX/bin/python -DPYTHON_INCLUDE_DIR=$PREFIX/include/python3.6m -DPYTHON_LIBRARY=$PREFIX/lib/libpython3.6m.a -DTORCH_BUILD_VERSION=1.6.0a0+445c276 -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_FBGEMM=0 -DUSE_LEVELDB=1 -DUSE_LMDB=1 -DUSE_MKLDNN=0 -DUSE_NNPACK=0 -DUSE_NUMPY=True -DUSE_OPENMP=1 -DUSE_PYTORCH_QNNPACK=0 -DUSE_QNNPACK=0 -DUSE_SYSTEM_NCCL=1 -DUSE_TENSORRT=0 -DUSE_XNNPACK=0 $SRC_DIR
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBLAS=OpenBLAS', '-DBUILD_CUSTOM_PROTOBUF=OFF', '-DBUILD_PREFIX=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_build_env', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Unix Makefiles', '-DCMAKE_INSTALL_PREFIX=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work/torch', '-DCMAKE_PREFIX_PATH=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/;/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol', '-DNUMPY_INCLUDE_DIR=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python', '-DPYTHON_INCLUDE_DIR=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/python3.6m', '-DPYTHON_LIBRARY=/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libpython3.6m.a', '-DTORCH_BUILD_VERSION=1.6.0a0+445c276', '-DUSE_CUDA=0', '-DUSE_CUDNN=0', '-DUSE_FBGEMM=0', '-DUSE_LEVELDB=1', '-DUSE_LMDB=1', '-DUSE_MKLDNN=0', '-DUSE_NNPACK=0', '-DUSE_NUMPY=True', '-DUSE_OPENMP=1', '-DUSE_PYTORCH_QNNPACK=0', '-DUSE_QNNPACK=0', '-DUSE_SYSTEM_NCCL=1', '-DUSE_TENSORRT=0', '-DUSE_XNNPACK=0', '/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/apps/open-ce-v1.0.1/open-ce/open-ce/build_feedstock.py", line 186, in build_feedstock
    config=config, variants=variant)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 2132, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/apps/anaconda3/envs/open-ce/conda-bld/pytorch-base_1605588479782/work/conda_build.sh']' returned non-zero exit status 1.
Failure building recipe: pytorch-base
Unable to build recipe: pytorch-feedstock

**Comment by cdeepali** [comment]
Looks like PyTorch build is picking up `Ninja` installed on your system. 
Could you add `export USE_NINJA=0` at  https://github.com/open-ce/pytorch-feedstock/blob/master/recipe/build.sh#L64 and try the build. 

Or else you may try the `--docker-build` option as suggested by @bnemanich.

**Comment by cdeepali** [comment]
@superdavidxp, were you able to give this a try again?
