### ISSUE TITLE
Upgrade DALI to 0.28

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#183]
Upgrade DALI to version 0.27.

**Comment by npanpaliya** [comment]
DALI 0.28 is tagged today. So, I think we should move to that. As of now I'm seeing issues building DALI 0.27 with protobuf 3.13. I'll try DALI 0.28 now.

**Comment by npanpaliya** [comment]
As per this [link](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#compiling-dali-from-source-bare-metal), supported protobuf is 3.11.

**Comment by npanpaliya** [comment]
Just found out that protobuf has separated out static libs into a separate package for 3.13. So, packages needing protobuf's static libs should also include a dependency on `libprotobuf-static`.
