### ISSUE TITLE
[BUG] Cannot install open-ce with python 3.6.10

### ISSUE THREAD

**Issue by taesunmoon-yktn** [open-ce/open-ce#197]
**Describe the bug**
Attempting to install with this command ` ../open-ce/open-ce build env ../envs/opence-env.yaml`
results in this error:
```
Traceback (most recent call last):
  File "../open-ce/open-ce", line 93, in <module>
    _main()
  File "../open-ce/open-ce", line 84, in _main
    parser = make_parser()
  File "../open-ce/open-ce", line 27, in make_parser
    required=True)
  File "/home/tsmoon/.conda/envs/lang-model1/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

**To Reproduce**
Use python 3.6.10 to reproduce the above.

Judging by the api definition in https://docs.python.org/3.6/library/argparse.html#argparse.ArgumentParser.add_subparsers,  `required` is not an allowed keyword argument in 3.6

**Expected behavior**
Should have proceeded further.

**System (please complete the following information):**
 - OS: Linux 4.14.0-115.14.1.el7a.ppc64le
 - Architecture: Power

**Comment by jayfurmanek** [comment]
Thanks for reporting!
We'll work on a fix. In the meantime, it should work with py37. Note that this does not mean all of the resulting packages will be built against py37 as that is controlled by the input parameters.

**Comment by bethune-bryant** [comment]
@taesunmoon-yktn 
This should be resolved in the master branch now. Please let us know if you run into any other issues.
