### ISSUE TITLE
[BUG] open-ce builds inside existing conda environment

### ISSUE THREAD

**Issue by taesunmoon-yktn** [open-ce/open-ce#198]
**Describe the bug**
Rather than depositing build files inside `local_files` as described in the main README, the build files are going to `$existing_conda_env/conda-bld`

**To Reproduce**
Instantiate a local conda environment.

Then create a `local_files` directory under `open-ce`. Fro there, execute `../open-ce/open-ce build env ../envs/opence-env.yaml`

**Expected behavior**
That all associated build files would go to a directory under `open-ce/local_files`

**Execution Logs**
Assuming the current conda environment resides in `$existing_conda_env`, the build log is peppered with statements such as
```source tree in: $existing_conda_env/conda-bld/_pytorch_select_1606936176597/work
Renaming work directory '$existing_conda_env/conda-bld/_pytorch_select_1606936176597/work' to '$existing_conda_env/conda-bld/_pytorch_select_1606936176597/work_moved__pytorch_select-1.0-cpu_1_linux-ppc64le_main_build_loop'
INFO:conda_build.utils:Renaming work directory '$existing_conda_env/conda-bld/_pytorch_select_1606936176597/work' to '$existing_conda_env/conda-bld/_pytorch_select_1606936176597/work_moved__pytorch_select-1.0-cpu_1_linux-ppc64le_main_build_loop'
```

**System (please complete the following information):**
 - OS: Linux 4.14.0-115.14.1.el7a.ppc64le
 - Architecture: Power
 - python 3.6.10
 - conda 4.6.9

**Comment by bnemanich** [comment]
Hi,

The `local_files` directory is intended to store files that are needed for the build, not for the output of the build. To change the directory of where the packages will be generated, please pass the `--output_folder` arguments to `open-ce build env`. For more information on this, please see: https://github.com/open-ce/open-ce/blob/master/doc/README.open_ce_build.md#command-usage-for-open-ce-build-env

**Comment by bnemanich** [comment]
During a build, temporary files will be stored within `$existing_conda_env/conda-bld`.

**Comment by taesunmoon-yktn** [comment]
I'll try that out. Thanks!
