### ISSUE TITLE
[BUG] Config validation run via build env doesn't account cuda version being passed.

### ISSUE THREAD

**Issue by npanpaliya** [open-ce/open-ce#200]
**Describe the bug**
Validate config when run through build env doesn't account the cuda version being passed, instead uses the default one always.

**To Reproduce**
./open-ce/open-ce/open-ce build env --build_type=cuda --cuda_versions=11.0 ./open-ce/envs/dali-env.yaml

**Expected behavior**
validate_config run via build env takes default cuda argument instead of the one being passed.

**Execution Logs**
```
Validating /home/builder/open-ce/open-ce/../conda_build_config.yaml for open-ce/envs/dali-env.yaml : {'python': '3.6', 'build_type': 'cuda', 'mpi_type': 'openmpi', 'cudatoolkit': '10.2'}
Successfully validated /home/builder/open-ce/open-ce/../conda_build_config.yaml for open-ce/envs/dali-env.yaml : {'python': '3.6', 'build_type': 'cuda', 'mpi_type': 'openmpi', 'cudatoolkit': '10.2'}
```

**System (please complete the following information):**
 - OS: RHEL7/RHEL8
 - Architecture: ppc64le/x86

**Comment by npanpaliya** [comment]
https://github.com/open-ce/open-ce/blob/master/open-ce/build_env.py#L88 is missing `args.cuda_versions`.

**Comment by npanpaliya** [comment]
Included the fix in this PR https://github.com/open-ce/open-ce/pull/162

**Comment by jayfurmanek** [comment]
I noticed this. Thanks for fixing!
