### ISSUE TITLE
CuDNN 8 on X86 missing memcpy reference

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#236]
@cdeepali reported seeing the following error while building PyTorch for PYthon 3.8 on x86:

```
/home/deepch23/anaconda3/conda-bld/pytorch-base_1608825300544/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib64/libcudnn.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
```

It seems like CuDNN 8 on x86 also needs the memcpy_wrapper that is currently part of the TensorRT feedstock. This is only a problem on Python 3.8, because TensorRT is not being used with PyTorch with Python 3.8.

The memcpy_wrapper should be moved from the TensorRT feedstock to the CuDNN feedstock. It will still get pulled into TensorRT since CuDNN is a dependency for TensorRT.

**Comment by npanpaliya** [comment]
I think we should put those memcpy and clocktime wrappers to a new and separate repository.

**Comment by jayfurmanek** [comment]
@cdeepali In your build tests, did you move the wrapper to it's own repo, or was it in the cudnn repo?

**Comment by cdeepali** [comment]
@jayfurmanek, I just had local changes to enable it. I had not moved it it was under TRT itself.
