### ISSUE TITLE
PyAV Feedstock 

### ISSUE THREAD

**Issue by richardtml** [open-ce/open-ce#25]
Thanks for the repos! 

Could you please provide a feedstock for [PyAV](https://github.com/PyAV-Org/PyAV)? It's a PyTorch official [dependency](https://pytorch.org/docs/stable/torchvision/index.html#torchvision.set_video_backend) to read video, however, ppc64le is disabled in [conda-forge](https://github.com/conda-forge/av-feedstock) channel.

**Comment by jayfurmanek** [comment]
Thanks for the request @richardtml !
We are currently looking at some of the obscure packages needed within the TF and PyTorch ecosystems for a complete environment, so thanks for the highlight on `PyAv`.

A couple observations:
 - `torchvision` needs to be build with ffmpeg support enabled
 - PyAv looks to be 100% python, so it should work well as a noarch pkg across arch's

ffmpeg is fairly complex and has a lot of function of various licenses and some of which is patent encumbered. Luckily, Anaconda, does offer ffmpeg . We'll do some testing on if `torchtext`+`PyAv` works with Anaconda's `ffmpeg` without issue and if so, we'll pull PyAv in.

**Comment by richardtml** [comment]
Thank you @jayfurmanek , I will keep an eye on this issue to test it as as soon as you publish it.

**Comment by cdeepali** [comment]
@richardtml,  `torchvision` with `av` backend enabled is now available for test.

**Comment by richardtml** [comment]
Thank you @cdeepali, I'll test it asap.

**Comment by cdeepali** [comment]
Sure, Thanks @richardtml.

**Comment by bnemanich** [comment]
Closing this issue, since `av` was added. @richardtml if you run into any problems, please create a new issue.
