### ISSUE TITLE
Create a public Slack workspace for Open-CE development.

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#253]
Setup a public Slack workspace for Open-CE development.

Modify documentation to describe how a user would access the workspace.

**Comment by jayfurmanek** [comment]
open-ce.slack.com

**Comment by jayfurmanek** [comment]
Shared invite links only last 30 days so we'll need to continually update.

**Comment by jayfurmanek** [comment]
Shared invite links only last 30 days so we'll need to continually update.
