### ISSUE TITLE
Move Open-CE build tools to a separate repo from the Open-CE environment files.

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#257]
The Open-CE build tools and default Open-CE environment files should be kept within separate repositories, and versioned differently.

This issue should:
1. Determine the naming of the repositories.
2. Move the appropriate code to the approrpiate repositories.
3. Create plan for keeping Open-CE environment files backwards compatible with future Open-CE build tools.
4. Determine versioning scheme for Open-CE build tools.

**Comment by bethune-bryant** [comment]
## Naming
I think we should leave the name of the tools repo as `open-ce` and create a new repo to store the environment files called `environments`.

## Backwards Compatibility
The first line of an environment file can be an open-ce version string. The `open-ce` tools can check that version and provide users with errors if the current tools being used are the wrong version.

```
# open-ce>=1.1|<1.2

{% if build_type == 'cuda' %}
imported_envs:
  - tensorrt-env.yaml
{% endif %}

packages:
  - feedstock : pytorch
{% if build_type == 'cuda' %}
  - feedstock : nccl
{% endif %}
  - feedstock : sentencepiece

```

It may also be possible to add some PR tests that perform some backwards compatibility checks.

## Versioning for Tools
Having seperate versioning for the tools could be confusing for users. I think we should discuss this.

**Comment by dllehr81** [comment]
Would it make sense to do the opposite?  And put an env file version?  And have the open-ce tool determine if the env file is compatible with the version of open-ce?  sort of like how a lot of yaml files, etc.  have an `apiVersion` tag to signify what should be used?

**Comment by bethune-bryant** [comment]
> 
> 
> Would it make sense to do the opposite? And put an env file version? And have the open-ce tool determine if the env file is compatible with the version of open-ce? sort of like how a lot of yaml files, etc. have an `apiVersion` tag to signify what should be used?

Are you thinking something like, call what we have now API1.0, if we ever make a compatibility breaking change to the env files, call it API2.0

I like that too, but adding a third version could lead to even more confusion.
