### ISSUE TITLE
Update TensorFlow to 2.5.

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#264]
When the RC is available for TensorFlow 2.5 start working on updating TensorFlow and dependencies.

**Comment by jayfurmanek** [comment]
We also need to review the patches we have in the recipe. Many were left over from when we were going to vender cudatoolkit (as cudatoolkit-dev) - helping bazel find cuda in the conda environments.
Now we build with cuda installed locally, so those patches can be removed.

We should also make sure to keep the serving recipe in sync with the TF recipe as far as patches go.
