### ISSUE TITLE
Update PyTorch to 1.8

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#265]
When the RC for PyTorch 1.8 is available, start working on updating PyTorch and its dependencies.

**Comment by cdeepali** [comment]
The following packages need to be updated:
- [ ] PyTorch v1.8.0
- [ ] vision v0.9.0
- [ ] text v0.9.0-rc5
- [ ] av v8.0.3
- [ ] pytorch-lightning v1.2.2
- [ ] pytorch-lightning-bolts v0.3.0
- [ ] package pins in open-ce-environments

**Comment by tileb1** [comment]
Hello, is there an expected timeline for this PR? I'm particularly interested in torchvision v0.9.1

**Comment by jayfurmanek** [comment]
Sorry for the delay. We had to deal with the new cos7 based x86 toolchains that Anaconda released recently.

We hope to merge these in this week.
