### ISSUE TITLE
[REQUEST] Automatically generate HTML webpages for generated channels.

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#268]
**Is your feature request related to a problem? Please describe.**
The default channel browser is clunky and not very robust.

**Describe the solution you'd like**
Some community members have come up with ways to generate some more functional web pages for the generated channel. It would be good to have this kind of feature built into the tools.

**Additional context**
MIT Satori Channel: https://opence.mit.edu/
OSU Channel: https://osuosl.org/services/powerdev/opence/

**Comment by jayfurmanek** [comment]
I think the license and meta information is important here, but maybe doesn't have to be on the front end HTML.
If we decide it doesn't belong on the channel browser page, we could collect it in an output file along with our conda env file output.

**Comment by alexlang74** [comment]
Closing, as no intent to address in the foreseeable future. May open a separate item to create a (more static) HTML page with install instructions...
