### ISSUE TITLE
Verify that all feedstocks are setup properly

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#272]
All Open-CE feedstocks should be setup in the following manner:

https://github.com/open-ce/open-ce/blob/master/doc/README.feedstock_setup.md

Some of the feedstocks do not have branch permissions setup properly. Go through each feedstock and verify that they are consistent with the rules above.

**Comment by jayfurmanek** [comment]
Branch Protections and Merging options set for all repos according to the README.
