### ISSUE TITLE
[Suggestion] Rename master branch to main

### ISSUE THREAD

**Issue by rolweber** [open-ce/open-ce#290]
Could we follow GitHub's lead? Shouldn't be much effort.
https://github.com/github/renaming/blob/main/README.md

**Comment by jayfurmanek** [comment]
yeah, some of our newer repos have main instead of master already (once github made it the default). It's probably a good idea to make them all main if for nothing else than consistency.

**Comment by rolweber** [comment]
Great, I like it :-)
The best time would be when there are no more open PRs against master.

**Comment by dncliss** [comment]
The different branch renames were all done via script, in place, not requiring PRs to be submitted for this item.  HOWEVER, the workflows for most of the feedstocks did have `master` hardcoded in their yaml files, requiring PRs to change the names.  This resulted in 44 essentially identical PRs.  Those were handled in bulk, and they don't explicitly point back to this request issue, but for completeness/documentation purposes here they are, listed:

https://github.com/open-ce/DALI-feedstock/pull/20
https://github.com/open-ce/av-feedstock/pull/8
https://github.com/open-ce/bazel-feedstock/pull/10
https://github.com/open-ce/cdts-feedstock/pull/14
https://github.com/open-ce/cudnn-feedstock/pull/11
https://github.com/open-ce/dm-tree-feedstock/pull/8
https://github.com/open-ce/horovod-feedstock/pull/20
https://github.com/open-ce/jpeg-turbo-feedstock/pull/9
https://github.com/open-ce/libevent-feedstock/pull/8
https://github.com/open-ce/libflac-feedstock/pull/9
https://github.com/open-ce/libsndfile-feedstock/pull/9
https://github.com/open-ce/magma-feedstock/pull/13
https://github.com/open-ce/nccl-feedstock/pull/11
https://github.com/open-ce/numactl-feedstock/pull/12
https://github.com/open-ce/onnx-feedstock/pull/17
https://github.com/open-ce/open-ce/pull/344
https://github.com/open-ce/opencv-feedstock/pull/8
https://github.com/open-ce/openmpi-feedstock/pull/16
https://github.com/open-ce/protobuf-feedstock/pull/11
https://github.com/open-ce/pytorch-feedstock/pull/42
https://github.com/open-ce/pytorch-lightning-feedstock/pull/13
https://github.com/open-ce/rust-nightly-feedstock/pull/12
https://github.com/open-ce/sacremoses-feedstock/pull/7
https://github.com/open-ce/semantic-feedstock/pull/7
https://github.com/open-ce/sentencepiece-feedstock/pull/10
https://github.com/open-ce/spacy-feedstock/pull/14
https://github.com/open-ce/srsly-feedstock/pull/9
https://github.com/open-ce/tensorboard-feedstock/pull/14
https://github.com/open-ce/tensorboard-plugin-wit-feedstock/pull/7
https://github.com/open-ce/tensorflow-datasets-feedstock/pull/10
https://github.com/open-ce/tensorflow-estimator-feedstock/pull/10
https://github.com/open-ce/tensorflow-feedstock/pull/29
https://github.com/open-ce/tensorflow-hub-feedstock/pull/10
https://github.com/open-ce/tensorflow-metadata-feedstock/pull/9
https://github.com/open-ce/tensorflow-probability-feedstock/pull/10
https://github.com/open-ce/tensorflow-serving-feedstock/pull/22
https://github.com/open-ce/tensorflow-text-feedstock/pull/12
https://github.com/open-ce/tensorrt-feedstock/pull/19
https://github.com/open-ce/thinc-feedstock/pull/11
https://github.com/open-ce/tokenizers-feedstock/pull/10
https://github.com/open-ce/torchtext-feedstock/pull/17
https://github.com/open-ce/torchvision-feedstock/pull/23
https://github.com/open-ce/transformers-feedstock/pull/14
https://github.com/open-ce/xgboost-feedstock/pull/28

**Comment by bethune-bryant** [comment]
> 
> Or maybe GitHub's feature to rename is smart enough to adjust the PRs as well.

The rename was smart enough to adjust all in-flight PRs, which was nice!
