### ISSUE TITLE
[BUG] Unclear description of --docker_build option

### ISSUE THREAD

**Issue by rolweber** [open-ce/open-ce#291]
The help text for `--docker_build` currently says...
```txt
NOTE: When the --docker_build flag is used, all arguments with paths
      should be relative to the directory containing open-ce.
```
The command for starting a build as documented [in README.md](https://github.com/open-ce/open-ce/blob/master/README.md#building-a-collection-of-packages) is:
```bash
./open-ce/open-ce/open-ce build env open-ce/envs/opence-env.yaml
```
To which of these three directory levels does "open-ce" in the help text refer?

[In README.open_ce_build.txt](https://github.com/open-ce/open-ce/blob/master/doc/README.open_ce_build.md#open-ce-build-env-sub-command), there are still two levels to choose from:
```bash
./open-ce/open-ce build env envs/tensorflow-env.yaml
```

**Comment by npanpaliya** [comment]
`open-ce`  referred in the doc refers to the root open-ce folder which comes when we clone https://github.com/open-ce/open-ce and not the sub-directories of cloned open-ce repo. 
We will precisely mention that in the doc.

**Comment by npanpaliya** [comment]
This has been fixed in https://github.com/open-ce/open-ce/pull/296
