### ISSUE TITLE
[BUG] Improve documentation for "open-ce build feedstock"

### ISSUE THREAD

**Issue by rolweber** [open-ce/open-ce#292]
The documentation for ["open-ce build feedstock"](https://github.com/open-ce/open-ce/blob/master/doc/README.open_ce_build.md#open-ce-build-feedstock-sub-command) does not mention from which directory to run the command. It mentions that the feedstock to be built must be checked out locally. But the command doesn't expect a feedstock name or directory as argument (according to the documentation, I didn't try).

I got this working by calling the command from within the checked out feedstock directory.

Another thing that's unclear to me is how to provide the dependencies. Do they have to be built locally, or is it possible to provide artifacts that have been built elsewhere in the past? If the latter, how? Are the packages expected in the file channel where the output will be stored? Or do dependencies have to be installed in the current conda environment?

**Comment by rolweber** [comment]
Background: I'm trying to figure out how to build a single package that has been updated, without rebuilding the dependencies that have not changed.

**Comment by npanpaliya** [comment]
To build a single feedstock -
1. You need to check out that feedstock
2. Run the command `build feedstock` from within the checked out code of the feedstock like below -
```
../open-ce/open-ce/open-ce build feedstock --output_folder=/home/builder/condabuild 
```
Code from the repo `https://github.com/open-ce/open-ce` is to be present at the same level of the feedstock.

Above command will build tensorflow and put the output in the folder specified by output_folder. It will also pick up the needed dependencies from the output_folder if you'd built it in past. You can also provide `--channels` option to specify the channel from where dependencies can be picked up.
