### ISSUE TITLE
[REQUEST] Package the tools.

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#299]
**Describe the solution you'd like**
It would be much easier to use the tools if they were installable as a package.

If we do a pip package it can be installed directly from the github repo:

`pip install git+https://github.com/open-ce/open-ce.git@open-cev1.1`

We should also look into making a conda package as well.

**Comment by bethune-bryant** [comment]
A big part of this issue is reorganizing the repo into python package structure, and change how all the imports are happening across all the files. `open-ce` is not a valid identifier for import, so we'll have to make the name of the python library something like `opence`.

The next step will be adding the `setup.py` file and getting the right contents to the right places at install time. We'll want to make sure that the `open-ce` file ends up in bin, and the other `.py` files end up in lib. We'll also want to make sure that the docker files are installed to a place they can be found at runtime.

**Comment by npanpaliya** [comment]
Thanks @bethune-bryant - This will definitely help me in implementing this. 
I think this task can further be split as follows -
1. Reorganize the repo into python package structure
2. Change all the imports 
3. Add setup.py
4. Update documentation 
5.  Create conda package

**Comment by bethune-bryant** [comment]
That breakdown looks good, the only change I'd make is that the imports will have to change at the same time that the structure changes. With that change I think each of these tasks could be done separately.

1. Reorganize the repo into python package structure
    * Change all the imports
2. Add setup.py and other Manifest files needed for pip package
3. Update documentation
4. Create conda package

**Comment by npanpaliya** [comment]
Yes, actually while working on #1, I ended up doing #2 as well, so structural changes and import ones will go hand in hand.

 Also, I think open-ce-environments has to be packaged as well.

**Comment by bnemanich** [comment]
Let's hold off on open-ce-environments. @bethune-bryant will be looking into the best way for those to be easily used.

**Comment by npanpaliya** [comment]
Sure.

**Comment by bethune-bryant** [comment]
> 
> 
> Let's hold off on open-ce-environments. @bethune-bryant will be looking into the best way for those to be easily used.

#298 is where that work is being tracked.

**Comment by npanpaliya** [comment]
I've a few doubts - 
1. I've included `git_tools` as well in the package as a module. Should I make it as a sub-module of open_ce package? If yes, I'll have to move it inside open-ce/open_ce directory.

open-ce (main repo)
   - open_ce
       - __init__.py
       - build_env.py
       - build_feedstock.py
       - ...
       - git_tools
          - __init__.py
          - apply_patches.py
          - create_opence_release.py
          - ...
2. Should we add a script like build_pip_package.sh which will create wheel file of open-ce?

**Comment by bethune-bryant** [comment]
>     1. I've included `git_tools` as well in the package as a module. Should I make it as a sub-module of open_ce package? If yes, I'll have to move it inside open-ce/open_ce directory.

I don't think we should include the `git_tools` in the package. Those are for managing the repo and feedstocks, and should really only be used within a clone of the repo.

>     2. Should we add a script like build_pip_package.sh which will create wheel file of open-ce?

This is probably a good idea. Initially we'll probably install directly from github, but eventually we'll probably want to make the package available somewhere. We'll probably also want a script to build the conda package, so we'll probably want a directory for them.
