### ISSUE TITLE
[REQUEST] Generate Filtered Dependency List

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#304]
For users who want to have a list of dependencies for a subset of packages it would be useful to have a feature that generates a list of dependencies for a given list of packages.

**Comment by bnemanich** [comment]
This could look something like:
1. Add a new `--packages` argument (or some other argument name).
2. It will still be necesary to pass an Open-CE environment file to the `open-ce build env` command, but the `--packages` argument can be used to only build the packages (and their dependencies) that are requested.

This should work for generating the conda environment file, as well as tests.

**Comment by jayfurmanek** [comment]
Maybe this could also lay some ground work on compiling licenses for this same set of packages in the list.
