### ISSUE TITLE
Modify Meta Package License Information

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#322]
The meta-packages within the following packages should be modified to have their license information match the base package. That way when someone looks for the license information for `tensorflow` it will show the same information as `tensorflow-base`. I believe that this is what users would expect to see.

- [ ] tensorflow
- [ ] pytorch
- [ ] py-xgboost
- [ ] lightGBM
- [ ] torchvision

**Comment by cdeepali** [comment]
@bnemanich, do we want to mimic the entire About section from the main package (excluding the 'license_file') along with the license information?
