### ISSUE TITLE
[REQUEST] opence option to specify bazel cache directory

### ISSUE THREAD

**Issue by adammoody** [open-ce/open-ce#324]
**Is your feature request related to a problem? Please describe.**
By default, bazel caches files it downloads to ``~/.cache/bazel``.  On the particular system where I build Open-CE, the home directory is small due to quota limits.  The Open-CE build eventually fails when it exhausts the available space in this file system.

**Describe the solution you'd like**
I would like to point bazel to use another cache directory.

I have been able to work around my problem by modifying the builds scripts that invoke bazel to set ``$TEST_TMPDIR`` like so:
```
diff --git a/recipe/build-pip-package.sh b/recipe/build-pip-package.sh
index 930d84b..d43facb 100644
--- a/recipe/build-pip-package.sh
+++ b/recipe/build-pip-package.sh
@@ -37,6 +37,9 @@ $SCRIPT_DIR/set_tensorflow_bazelrc.sh $SRC_DIR/tensorflow
 bazel clean --expunge
 bazel shutdown

+# tell bazel to use /dev/shm as its cache (rather than ~/.cache/bazel)
+export TEST_TMPDIR=/dev/shm/.cache
+
 bazel --bazelrc=$SRC_DIR/tensorflow/tensorflow.bazelrc build \
     --config=opt \
     --config=numa \
```
That variable is described here: https://docs.bazel.build/versions/master/output_directories.html

Could we add an option to the opence command to specify a different bazel cache directory?

**Describe alternatives you've considered**

**Additional context**

**Comment by adammoody** [comment]
Rather than setting ``$TEST_TMPDIR`` in the build script for each feedstock recipe, I found there is an ``--output_user_root`` option in bazel that one can use to set this path.

https://docs.bazel.build/versions/master/output_directories.html#current-layout
https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_user_root

This can be added to a global bazel resource file, e.g.,
``
echo "startup --output_user_root=/dev/shm/.cache" >> ~/.bazelrc
``

**Comment by adammoody** [comment]
I'm happy with this as a fix for my problem, so feel free to close this out.  And in particular, redirecting bazel to download and build software in ``/dev/shm`` vs something like NFS also should speed up the build.

This might be a useful troubleshooting tip in the docs in case others run into a similar problem.

**Comment by npanpaliya** [comment]
I and @jayfurmanek discussed this and decided that we will update the documentation for this. We will mention about $TEST_TMPDIR variable that can be used to change the bazel cache directory.

**Comment by alexlang74** [comment]
Done

**Comment by adammoody** [comment]
I just noticed the documentation includes a note about $TEST_TMPDIR.  Thanks, @npanpaliya and @alexlang74 .

For people who need to take this step, it may be easier to set ``--output_user_dir`` in the bazel resource file.  That's what I have switched to.

https://github.com/open-ce/open-ce/issues/324#issuecomment-782761891

That can be done once at a top-level rather than modifying each feedstock.

**Comment by alexlang74** [comment]
Thanks, @adammoody !
