### ISSUE TITLE
[QUESTION] List the specific conda release used in Docker image files?

### ISSUE THREAD

**Issue by adammoody** [open-ce/open-ce#328]
**Your question:**
To help with building past Open-CE releases, would it be possible to name a specific miniconda release (or note which one was used at the time) in the Docker image files rather than use the "latest"?

https://github.com/open-ce/open-ce/blob/open-ce-v1.1.2/images/builder-cuda-ppc64le/Dockerfile.cuda-10.2#L30

Even without it, one could likely deduce the conda that was used at the time based on the release date without a ton of effort.  It would just eliminate one source of errors.

Either way, thanks!

**Comment by alexlang74** [comment]
No intent to address any time soon

**Comment by cdeepali** [comment]
This is now included in builder - https://github.com/open-ce/open-ce-builder/commit/d85fecb67063c4ce9cc7d3996a3c084df8eea107
