### ISSUE TITLE
Add validate flag to Open-CE Environment files

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#340]
Removing the libprotobuf package from the build-config.yaml file of protobuf-feedstock causes the validate step to fail when calling `open-ce build env --python_versions 3.8` on a Power system. This is because googleapis-common-protos has a dependency on `protobuf`.

This is kind of an edge case, where Open-CE is building a package that is already found in the `defaults` channel, except the Open-CE package is an older version than what is in `defaults`. Our validate steps can't handle this case.

One option to handle this is add a `validate` flag to a `package` within an Open-CE environment file. When the value is `False`, the packages dependencies should not be added to the validate step. The default value of `validate` should be `True`.

**UPDATE:** We no longer need a `validate` flag within an environment file. But, we should add a flag that can be passed to `open-ce build env` that disables validation checks.

**Comment by alexlang74** [comment]
Closing, as no intent to fix
