### ISSUE TITLE
Update pylint version

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#341]
Update the version of pylint that is used during PR tests to 2.7.x.

Fix any issues that may arise with the newer version of pylint.

**Comment by npanpaliya** [comment]
@bnemanich 
After upgrading pylint to 2.7.x, most of the pylint errors are `invalid-name` pointing to the Enum keys we have defined in `env_config.py`, `test_feedstock.py` or `get_licenses.py`. I think changing all those keys everywhere will also need us change the environment files. So, I think we should add this error to the exception list. My PR for #329 already adds it in exception list (disabled in .pylintrc) as it was complaining for invalid name of `open-ce` file.

Other errors can be addressed for which I'll create a PR after merging my PR for #329.
