### ISSUE TITLE
[BUG] DAG Generation When Dependency Chain Includes External Dependencies

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce#345]
**Describe the bug**

![image](https://user-images.githubusercontent.com/18013846/110016046-3054fe00-7cea-11eb-9a4b-beec78ae89b1.png)

In the above dependency graph, let's say:

- A, B, C, E and F are all internal packages being built by `open-ce` 
- D is an external dependency that has a dependency on the internal package F

This would cause a race condition since the Open-CE tools won't know about the dependency of A and C on F.
The DAG generated by `open-ce` would show that no packages depended on F.

**Expected behavior**
We should look into adding external dependency traversing to find any later dependencies on internal packages.

**Comment by bnemanich** [comment]
This is related to #340
