### ISSUE TITLE
update tqdm pin

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#348]
Update `tdqm` pin to newer version. version `v4.56.0` is latest version available now.

**Comment by jayfurmanek** [comment]
We should probably update this (in 1.1 and main) - it looks like pandas1.0 support in tqdm didn't come until 4.42. 
Support for tf.keras was added then as well.

I don't see any compatibility break warning in tqdm (its basically just a python based progress bar tool) so it should be safe to update.
