### ISSUE TITLE
sentencepiece-static fails to build due to missing tcmalloc library in link

### ISSUE THREAD

**Issue by adammoody** [open-ce/open-ce#36]
Thanks for putting this together.

While trying to build pytorch, I am getting an error on sentencepiece-static when it fails to find tcmalloc_minimal during a link step:
```
Scanning dependencies of target sentencepiece-static
[  1%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.o
[  3%] Building CXX object src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o

<snip>

[ 66%] Built target sentencepiece-static
Scanning dependencies of target spm_export_vocab
[ 67%] Building CXX object src/CMakeFiles/spm_export_vocab.dir/spm_export_vocab_main.cc.o
[ 69%] Linking CXX executable spm_export_vocab

<snip>

conda-bld/torchtext_1600914241366/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: cannot find -ltcmalloc_minimal
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/CMakeFiles/spm_export_vocab.dir/build.make:86: src/spm_export_vocab] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:103: src/CMakeFiles/spm_export_vocab.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```
As a base, I am working from the following anaconda build script:
```
Anaconda3-2020.02-Linux-ppc64le.sh
```
Here are the sequence of commands I used to attempt the build:
```
<download and install TensorRT tarball into local_files>

bash ./Anaconda3-2020.02-Linux-ppc64le.sh -b -f -p $installdir

source $installdir/bin/activate
conda config --add default_channels https://repo.anaconda.com/pkgs/main
conda config --add default_channels https://repo.anaconda.com/pkgs/r
conda config --prepend channels https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
conda config --set always_yes true
conda install -y conda-build

export IBM_POWERAI_LICENSE_ACCEPT=yes

# Clone Open-CE from GitHub
git clone https://github.com/open-ce/open-ce.git

./open-ce/builder/build_env.py --build_types cuda open-ce/envs/pytorch-env.yaml
```
Is there another conda package I should install to provide this library or is it expected to be installed on the system?

**Comment by cdeepali** [comment]
The steps you've used are correct. 

Are you are seeing this on a baremetal or container? Could you please share your platform details.

**Comment by cdeepali** [comment]
Do you have google perf tools installed ?

**Comment by jayfurmanek** [comment]
There may be another leak in the Pytorch build where it is preferring system tools. We'll take a look. In the meantime can you try again with adding `--docker_build` to the `build_env` command?

**Comment by adammoody** [comment]
> 
> 
> Do you have google perf tools installed ? Do you see `Found TCMalloc` in the build output?

This is a build on baremetal.  It looks like it does find tcmalloc in a system location:
```
Found TCMalloc: /usr/lib64/libtcmalloc_minimal.so
```

**Comment by jayfurmanek** [comment]
Yeah, cmake is a pain. We're looking at a change that will explicitly disable TCmalloc here.

**Comment by adammoody** [comment]
So I can't easily build docker images on the system I'm using, but still looking into options there.

In the meantime, I installed sentencepiece from the IBM repo as an attempted work around.
```
conda install -y sentencepiece
```
That seems to have gotten past the torchtext dependency, but it then fails building torchvision, with an error like
```
anaconda/conda-bld/torchvision-base_1600970083287/work/torchvision/csrc/cpu/decoder/defs.h:12:10: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

<snip>

Failure building recipe: torchvision-base-mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -I$PREFIX/include -fdebug-prUnable to build recipe: torchvision-feedstockision-base-0.7.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```

**Comment by cdeepali** [comment]
Do you have `ffmpeg` installed as well?

Looks like it begins to build the video backend as it detects `ffmpeg` on the system, but the build fails subsequently because it doesn't find the required include files. 

We are working on enabling video backend for torchvision.

**Comment by cdeepali** [comment]
@adammoody, we have updated the `torchtext` recipe to disable `TCmalloc` usage and also updated `torchvision` recipe to pick up `ffmpeg` from the `conda` environment. 
Could you please give it a try once and let us know if it works in your environment.

**Comment by jayfurmanek** [comment]
@adammoody Any chance you were able to try this again?

**Comment by bnemanich** [comment]
I'm going to close this issue. @adammoody if you are still seeing this as a problem, please re-open the issu.e
