### ISSUE TITLE
[QUESTION] Install V1.2.0 with openmpi failure

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#412]
Hi,

I am trying to install v1.2.0 on our IBM P9 system with CUDA-10.2, however, the openmpi failed with following error messages. we do have openmpi-4.0.3 natively installed on the system. Could anyone give me some advice?

It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)

**Comment by superdavidxp** [comment]
I checked it seems something to do with IB setting, is there any where I can modify?

**Comment by bnemanich** [comment]
@bethune-bryant Is this still an issue?

**Comment by bnemanich** [comment]
We were unable to reproduce this issue.
