### ISSUE TITLE
Install tensorflow with unknown confict

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#414]
Hi,

I am trying to install tensorflow after built from opence-v1.2.0. The error message says there are conflicts during installtion but default to show which package caused the problem. Any advise please?

(opence-v1.2.0) [root@hal15 open-ce-v1.2.0]# conda install -c ./condabuild tensorflow
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by jayfurmanek** [comment]
Hi!
Any other details? Is this x86 or ppc64le?

Can you post the output of:
```
conda info
```
and
```
conda list
```

**Comment by superdavidxp** [comment]
(opence-v1.2.0) [root@hal-login ~]# conda info

     active environment : opence-v1.2.0
    active env location : /opt/apps/anaconda3/envs/opence-v1.2.0
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.10.0
    conda-build version : 3.20.3
         python version : 3.8.5.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=ppc64le
       base environment : /opt/apps/anaconda3  (writable)
      conda av data dir : /opt/apps/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le
                          https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-ppc64le
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-ppc64le
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/apps/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/apps/anaconda3/envs
                          /root/.conda/envs
               platform : linux-ppc64le
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.8.5 Linux/4.18.0-147.0.3.el7.ppc64le centos/7.7.1908 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False

**Comment by superdavidxp** [comment]
(opence-v1.2.0) [root@hal-login ~]# conda list
# packages in environment at /opt/apps/anaconda3/envs/opence-v1.2.0:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           2.0                  cuda10.2_1    file:///opt/apps/open-ce-v1.2.0/condabuild
asn1crypto                1.4.0                      py_0  
av                        8.0.2            py37haa86098_1    file:///opt/apps/open-ce-v1.2.0/condabuild
blas                      1.0                    openblas  
brotlipy                  0.7.0           py37h140841e_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.4.13            h6ffa863_1  
certifi                   2020.12.5        py37h6ffa863_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4           py37h6ffa863_1003  
click                     7.0                      py37_0  
cryptography              2.3.1            py37hc365091_0  
cudatoolkit               10.2.89              hfd86e86_1  
cudnn                     7.6.5_10.2           h9286eec_3    file:///opt/apps/open-ce-v1.2.0/condabuild
decorator                 5.0.6              pyhd3eb1b0_0  
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py37_1  
gmp                       6.2.1                h29c3540_0  
gnutls                    3.6.15               hd39c10c_0  
graphsurgeon              0.4.1                    py37_2    file:///opt/apps/open-ce-v1.2.0/condabuild
idna                      2.8                      py37_0  
jpeg                      9b                   hcb7ba68_2  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h2045e0b_0  
leveldb                   1.20                 hf484d3e_1  
libedit                   3.1.20210216         h140841e_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 8.2.0                h822a55f_1  
libgfortran-ng            7.3.0                h822a55f_1  
libidn2                   2.3.0                h140841e_0  
libopenblas               0.3.13               h989ec91_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.11.2               hd408876_0  
libstdcxx-ng              8.2.0                h822a55f_1  
libtasn1                  4.16.0               h140841e_0  
libtiff                   4.1.0                h2733197_1  
libunistring              0.9.10               h140841e_0  
libvpx                    1.7.0                hf484d3e_0  
lmdb                      0.9.29               h29c3540_0  
lz4-c                     1.9.3                h29c3540_0  
nccl                      2.7.8                cuda10.2_4    file:///opt/apps/open-ce-v1.2.0/condabuild
ncurses                   6.2                  he6710b0_1  
nettle                    3.7.2                hdc176a3_1  
networkx                  2.3                        py_0  
numactl                   2.0.12               h459fe5f_2    file:///opt/apps/open-ce-v1.2.0/condabuild
numpy                     1.19.2           py37h6163131_0  
numpy-base                1.19.2           py37h75fe3a5_0  
olefile                   0.46                     py37_0  
onnx                      1.6.0                    py37_6    file:///opt/apps/open-ce-v1.2.0/condabuild
openh264                  2.1.0                hd408876_0  
openssl                   1.0.2u               h7b6447c_0  
pillow                    8.1.2            py37h3f95422_0  
pip                       21.0.1           py37h6ffa863_0  
protobuf                  3.11.2           py37he6710b0_0  
pycparser                 2.20                       py_2  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.0                h80c5aff_3  
pytorch                   1.7.1           cuda10.2_py37_3    file:///opt/apps/open-ce-v1.2.0/condabuild
pytorch-base              1.7.1           cuda10.2_py37_14    file:///opt/apps/open-ce-v1.2.0/condabuild
pyyaml                    5.4.1            py37h140841e_1  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_1  
scipy                     1.4.1            py37habc2bb6_0  
sentencepiece             0.1.91                   py37_3    file:///opt/apps/open-ce-v1.2.0/condabuild
setuptools                52.0.0           py37h6ffa863_0  
six                       1.15.0           py37h6ffa863_0  
snappy                    1.1.8                he6710b0_0  
sqlite                    3.33.0               hbc83047_0  
tabulate                  0.8.9            py37h6ffa863_0  
tensorrt                  7.0.0.11        cuda10.2_py37_5    file:///opt/apps/open-ce-v1.2.0/condabuild
tk                        8.6.10               hbc83047_0  
torchtext                 0.8.1                    py37_4    file:///opt/apps/open-ce-v1.2.0/condabuild
torchvision-base          0.8.2           cuda10.2_py37_6    file:///opt/apps/open-ce-v1.2.0/condabuild
tqdm                      4.59.0             pyhd3eb1b0_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
uff                       0.6.5                    py37_2    file:///opt/apps/open-ce-v1.2.0/condabuild
urllib3                   1.25.11                    py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                hc52992f_0

**Comment by jayfurmanek** [comment]
I see you have the IBM WML-CE channel enabled as well.
You may want to either remove that one from your .condarc, or put your local channel into your .condarc at a higher priority than the WML-CE channel. That might be the source of your conflicts.

**Comment by superdavidxp** [comment]
Thank you for your reply, I removed the IBM repos and it worked.
