### ISSUE TITLE
[REQUEST] Python 3.9 support

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/open-ce#420]
**Is your feature request related to a problem? Please describe.**
Many packages support Python3.9 now. Open-CE only guarantees builds up to py38

**Describe the solution you'd like**
Add py39 support for everything

**Additional context**
https://www.python.org/dev/peps/pep-0596/

**Comment by jayfurmanek** [comment]
For spacy, the following pins confict/need loosened updated for py69
 - plac - pin at 0.9.6, but py39 version available at 1.2.0 and higher
 - catalogue - pin at 1.0.0, but py39 version available at 2.0.2 and higher
 - requests - pin is at 2.22, and it goes noarch after 2.23.

**Comment by jayfurmanek** [comment]
@cdeepali When you get a change can you try these pin updates for spacy against your spacy 3 update?

**Comment by jayfurmanek** [comment]
`lightgbm` and `xgboost` both seem to build ok once the `setuptools` and `scipy` pins are updated

**Comment by jayfurmanek** [comment]
FYI
It looks like there is an issue with scipy >=1.6 and scikit-learn

https://github.com/scikit-learn/scikit-learn/issues/19787#issuecomment-810924873

**Comment by jayfurmanek** [comment]
There is scipy 1.5.2 for py39. We also loosen the scipy pin in: https://github.com/open-ce/open-ce/pull/439

**Comment by bnemanich** [comment]
Python 3.9 has been enabled in Open-CE 1.3.
