### ISSUE TITLE
[1.3] Add CUDA 11.2 support

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/open-ce#422]
Let's refresh CUDA to 11.2. Here's the list of work needed:
 - [x] include recipe to build `cudatoolkit` 11.2 since its not included in `defaults` yet and the timing there is unknown.  https://github.com/open-ce/open-ce/issues/394
 - [ ] Add an Open-CE env file to build cudatoolkit.
 - [ ] update the images in open-ce-builder to include a cuda11.2 base image for building
 - [x] update the conda_build_config.yaml file
 - [ ] fix/enable all cuda recipes for cuda 11.2

**Comment by npanpaliya** [comment]
I'm working on updating TF and family for cuda 11.2.
I'll pick up checkpoint#3 above - updating the images n open-ce-builder to include cuda 11.2 base image.

**Comment by jayfurmanek** [comment]
complete! Will revisit TensorRT in a future issue.
