### ISSUE TITLE
[BUG] Pytorch import fails with "Illegal instruction"

### ISSUE THREAD

**Issue by ckyleda** [open-ce/open-ce#430]
**Describe the bug**
Importing pytorch in an opence environment results in python immediately executing with "Illegal Instruction".

**To Reproduce**
Follow standard installation guide and create an environment via: 

`conda create --name opence pytorch=1.7.1 -y`

**Expected behavior**
Pytorch should be imported.

**System (please complete the following information):**
 - OS: [Linux]
 - Architecture [Power9]

**Comment by bethune-bryant** [comment]
Hi @ckyleda thank you for reporting this.

Did you build pytorch yourself or are you pulling from a pre-built open-ce channel somewhere?

Does the error occur when running the `conda create` command, or when you try to use pytorch in a python script?

What version of conda are you using?

Can you provide the output with the error?

**Comment by ckyleda** [comment]
> Hi @ckyleda thank you for reporting this.
> 
> Did you build pytorch yourself or are you pulling from a pre-built open-ce channel somewhere?
> 
> Does the error occur when running the `conda create` command, or when you try to use pytorch in a python script?
> 
> What version of conda are you using?
> 
> Can you provide the output with the error?

Hi,

Pulling from pre-built channels: https://opence.mit.edu / https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/

(Following: https://mit-satori.github.io/satori-ai-frameworks.html#wml-ce-and-open-ce-setting-up-the-software-repository)

Error occurs when trying to use pytorch in a python script.

Conda version is 4.9.2

Unfortunately the output error is simply "Illegal Instruction" - then python terminates with no further output.

**Comment by jayfurmanek** [comment]
Yeah if you could post the out from the “conda info” and “conda list” commands that would be good too.

**Comment by bethune-bryant** [comment]
I tried recreating your issue locally, and it looks like the latest pytorch in the MIT channel is 1.3.1.

When you're installing 1.7.1 it has to be getting it from somewhere else.

It would be good to get the output from `conda info` and `conda list`.

**Comment by ckyleda** [comment]
Hi,

I've managed to get this working now.

The key was checking conda info suggested by @jayfurmanek; there was an additional "early access" channel in there that was screwing things up.

  - https://opence.mit.edu
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  **- https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/linux-ppc64le/**
  - defaults

I can confirm that (at least I can import) pytorch 1.7.1. The MIT Channel has both 1.6.0 and 1.7.1

Cheers everyone.

**Comment by bethune-bryant** [comment]
@ckyleda 
Great news, let us know if you run into any other issues!
