### ISSUE TITLE
Auto Tag Releases

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#443]
Create a git action that will:

* Look to see if the `git_tag_for_env` flag has been modified within the `envs/opence-env.yaml` file.
* If it has, tag all of the feedstocks referenced within the opence-env.yaml file with the new tag. The old tag should be used to determine which branches of the feedstocks to tag.
* A pre-merge action should exist that lists what will be tagged, without doing the tagging.
* A post-merge action should exist that does the tagging, as well as tagging the open-ce repo and creating a release.

If it is determine that this is too dangerous to be done automatically, modify the existing scripts to do everything listed above, but don't use a post-merge github action.

**Comment by bnemanich** [comment]
Bonus points if you can get a list of all of the commits/PRs that will be part of the next release!

**Comment by bethune-bryant** [comment]
The main part is done, but I'd like to look into automatically generating the release notes.
