### ISSUE TITLE
Ensure all packages use `PKG_HASH` within their build string

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#518]
All packages should have `PKG_HASH` somewhere in their build string. This will ensure that packages are re-built when there has been a change in a package dependency version.

There is one downside to this. `noarch` packages built on different platforms will have different build strings. This will cause there to be some duplicate `noarch` packages when combining channels built on different platforms. Most of these `noarch` packages are very small, so this shouldn't take up too much extra space.

**Comment by cdeepali** [comment]
This is complete.
