### ISSUE TITLE
[QUESTION] Can not build cuDNN in OpenCE-v1.3.1 on ppc64le

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#519]
Dear All,
I tried to build opence-v1.3.1 on our ppc64le machine but failed.

the error message looks like this:
```
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/miniconda3/envs/tempo/conda-bld/cudnn_1632001973774/work/conda_build.sh']' returned non-zero exit status 4.
[OPEN-CE-ERROR]-11 Unable to build recipe: cudnn-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: cudnn8.0.5
```
if I execute the script, the error occurs when
```
(tempo) [root@hal13 open-ce-open-ce-v1.3.1]# /opt/miniconda3/envs/tempo/conda-bld/cudnn_1632001973774/work/conda_build.sh
mkdir: cannot create directory ‘/opt/miniconda3/envs/tempo/conda-bld/cudnn_1632001973774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include’: File exists
```
Please help me to solve this issue, Thank you in advance.

**Comment by superdavidxp** [comment]
Following-up questions, I have installed CUDA-11.0 and cuDNN 8.0.5 in my system, why the building system still building `cudnn-10.2-linux-ppc64le-v8.0.5.39_ce128ea090.tgz`

**Comment by cdeepali** [comment]
Please pass CUDA version as argument to the build command - `--cuda_versions 11.0`.  
More Details - https://github.com/open-ce/open-ce-builder/blob/main/doc/README.cuda_support.md#specifying-cuda-version

**Comment by superdavidxp** [comment]
@cdeepali Thank you for your help. I passed `--cuda_version 11.2` and it worked for building pytorch. However, when I building tensorflow, I got the error as following. Thank you in advance for your help.
```bazel build --enable_runfiles build_pip_pkg
+ bazel build --enable_runfiles build_pip_pkg
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Analyzing: target //:build_pip_pkg (1 packages loaded, 0 targets configured)
INFO: Repository local_config_cuda instantiated at:
  /opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/WORKSPACE:20:15: in <toplevel>
Repository rule cuda_configure defined at:
  /opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl:1091:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl", line 1089, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl", line 847, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx)
	File "/opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl", line 630, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl", line 1079, column 28, in find_cuda_config
		auto_configure_fail("Failed to run find_cuda_config.py: %s" % exec_result.stderr)
	File "/opt/miniconda3/envs/tempo/conda-bld/tensorflow-addons-ext_1632170575077/work/build_deps/toolchains/gpu/cuda_configure.bzl", line 261, column 9, in auto_configure_fail
		fail("\n%sCuda Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib64'
        '/lib64/power9'
        '/usr'
        '/usr/lib64//bind9-export'
        '/usr/local/cuda-11.0/targets/ppc64le-linux/lib'
```

**Comment by cdeepali** [comment]
Looks like this is baremetal build. Have you installed CUDA 11.2 on the system? 

In your earlier comment you've mentioned that you have installed CUDA 11.0.  If CUDA 11.0 is installed then please pass `--cuda_versions 11.0` to the build command. Also `CUDA_HOME` variable needs to be set for baremetal builds. 

Alternatively you can build on a container. To build on a container you can pass `--container_build` option to the build command. When combined with `--build_types cuda`, this option will create a CUDA enabled image and build recipes with CUDA support.

**Comment by superdavidxp** [comment]
@cdeepali Thank you for your reply, I did install the CUDA 11.2 on our system and the previous run of `open-ce build env --build_types cuda --cuda_versions 11.2 ./envs/pytorch-env.yaml` worked.

**Comment by cdeepali** [comment]
Do we have CUDA_HOME set?

**Comment by npanpaliya** [comment]
@superdavidxp - In your TF build log, I see you've `/usr/local/cuda-11.0` . Do you have 11.0 or 11.2 installed?

**Comment by superdavidxp** [comment]
@npanpaliya @cdeepali Thank you for your help. I have fixed this problem. I create a link `ln -s /usr/local/cuda-11.2 /usr/local/cuda`. The builder is looking for the default CUDA path, which seems confusing for a system with multiple CUDA installations.
