### ISSUE TITLE
[REQUEST] Pytorch Geometric Support

### ISSUE THREAD

**Issue by fmocking** [open-ce/open-ce#538]
Would it possible to provide integrate and distribute [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/) with open-ce. It provides enormous amount of resources and models for Graph Neural Networks. It is also crucial to support relative packages outlined in the [installation page](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html), namely, torch-scatter, torch-sparse, and torch-spline-conv. 

PS: I've attempted to build from source but no luck so far. 

Thank you for reviewing the request.

**Comment by alexlang74** [comment]
Added as part of OpenCE 1.6, @fmocking
