### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by penningt** [open-ce/open-ce#547]
**Your question:**
Is there still support for CUDA 10.2 in the latest OpenCE conda channel release (1.3.1)? I only see pytorch and tensorflow packages for 11.0 and 11.2

Thanks

**Comment by npanpaliya** [comment]
Are you looking at https://ftp.osuosl.org/pub/open-ce/current/linux-ppc64le/ channel? I see it has only 11.0 and 11.2 compatible packages. But we do support cuda 10.2 as well in our 1.3.1 as well as 1.4.0 release.

**Comment by npanpaliya** [comment]
You can also use this channel https://opence.mit.edu/#/. It has got all of TF versions that various releases of Open-CE support, built for cuda 10.2.

**Comment by penningt** [comment]
Thank you Nishidha. It does look like the mit channel has the versions of TF and pytorch that we need.
