### ISSUE TITLE
Fixes to include for any further releases for 1.4 

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#568]
The following fixes are added in 1.5 branch. These would need to be added to 1.4 in case of further releases on it. 

- https://github.com/open-ce/open-ce/issues/563
- https://github.com/open-ce/open-ce-builder/pull/108/commits/4371b43debe5b084cc01ea1ad625b00d0e3bbe4e

**Comment by alexlang74** [comment]
No plan to update 1.4 any further
