### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#570]
- [x]  Add feedstock for ORC v1.7.*
- [x]  Refresh snapml to v1.8.3
- [x] Refresh PyTorch to v1.10.1  
- [x] Refresh torchtext to v0.11.1
- [x] Refresh torchvision to v0.11.2
- [x] Rrefresh pytorch-lightning to v1.5.6 and check fsspec pin. 
- [x] Refresh torchmetrics to v0.6.2 and check setuptools pin. 
- [x] Refresh pydeprecate to 0.3.2 
- [x] Enable uwsgi for py39
- [x] Update werkzeug to 2.*
- [x] Update tensorflow-io-gcs-filesystem to 0.23
- [x] Sanity test for tensorflow-io-gcs-filesystem
- [x] Update tensorflow text to 2.7.2
- [x] Update LightGBM to 3.3.1
- [x] remove avoid python 3.10 blocks from the recipes. 
- [x] remove py36 blocks and dataclasses from all recipes
- [x] Refresh spacy to v3.2.1
- [x] Update tensorflow metadata to 1.5
- [x] Add orc feedstock to build orc v1.7
- [x] Update orc pin in pyarrow
- [x] Verify pyarrow build with orc 1.7 on x390x
- [x] Update DALI to 1.9
- ~[x] Update DALI to 0.10-dev~
- ~[ ]  Verify pyarrow 6 build on s390x~
- ~[x]  Update to pyarrow 6 if it builds with protobuf 3.14~

**Comment by rolweber** [comment]
How about refreshing tensorflow-metadata? Open CE 1.5.0 had version 1.0.0, latest is 1.5.0:
https://pypi.org/project/tensorflow-metadata/#history

**Comment by npanpaliya** [comment]
Yes, we can.

**Comment by cdeepali** [comment]
We decided to continue with pyarrow 5 for OpenCE 1.5.1.

**Comment by cdeepali** [comment]
Closing this as this is complete.
