### ISSUE TITLE
[FEEDSTOCK REQUEST] apache-beam support

### ISSUE THREAD

**Issue by mgiessing** [open-ce/open-ce#583]
**Describe the package you'd like added**
The package I'd like to add would be apache-beam https://github.com/apache/beam
It is a unified model for defining both batch and streaming data-parallel processing pipelines.

**Describe how this package fits in with the project**
As there is no conda / conda-forge packages for ppc64le of apache-beam it'd be helpful to provide it here.

**Additional context**
apache-beam seems also to have a conda-forge feedstock -> https://github.com/conda-forge/apache-beam-feedstock
In general I'm able to build it on ppc64le, but probably with wrong settings as I get an error when I'm importing it.

```
(py37) root@e4052ec10bcd:/# python
Python 3.7.11 (default, Jul 27 2021, 15:02:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apache_beam as ab
<jemalloc>: Unsupported system page size
```

**Comment by npanpaliya** [comment]
We have a PR that adds an inital recipe of Apace-beam - https://github.com/open-ce/apache-beam-feedstock.
Verified import of apache-beam.

**Comment by alexlang74** [comment]
Delivered in OpenCE 1.7.3
