### ISSUE TITLE
Release 1.5.2

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#584]
- [x] pip issue. - https://github.com/open-ce/open-ce/issues/587
- [x] Relax Numpy pin to allow both 1.20 and 1.22
- [x] tensorFlow 2.7.1
- [x] pytorch 1.10.2
- [x] xgboost 1.5.2
- [x] LightGBM 3.3.2
- [X] OpenCV 4.5.5
- [x] Remove pillow pin
- [X] Support protobuf 3.19.1
- [x] New library: mamba

**Comment by alexlang74** [comment]
Shipped!
