### ISSUE TITLE
Release 1.6 

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#586]
### Contents
- [x] TF / Keras 2.8
- [x] PyTorch ~1.11~ 1.10.2, due to unresolved https://github.com/pytorch/pytorch/issues/74614
- [x] PyArrow 7
- [x] Dali ~1.11~ 1.10
- [x] ONNX 1.11
- [x] ONNX Runtime 1.11 
- [x] Horovod 0.24.2
- [x]  SnapML 1.9
- [x] Transformers 4.17.0
- [ ] Other key libraries as they become available
     - [ ] LightGBM 3.4
     - [ ] OpenCV 4.6
     - [ ] XGBoost 1.6
- [ ] All security vulnerabilities (unless blocked by Anaconda dependencies)
- [ ] Add libraries from community requests. 
     - [x] PyTorch Geometric https://github.com/open-ce/open-ce/issues/538
     - [x] ray
     - [ ] Apache beam (pending investigation)
- [ ] Add further community candidates, if time permits:
     - [ ] cuda toolkit dev
     - [ ] DeepSpeed
     - [ ] Jax
     - [ ] Apache Beam
     - [ ] tslearn
 
### Environments
Python:
- [x]  Python 3.7: No longer built, recipes are no longer tested to work against Py37
- [ ] ~Support Python 3.10~  --> moved to openCE 1.7
  - [ ] Update GitHub Actions to Python 3.10 (optional)

CUDA: 
- [x] Drop support for CUDA 10.2
- [ ] ~Add support for CUDA 11.6~ --> Moved to openCE 1.7

Power:
- [ ] Support "heritage" libs that work on P8/P9/P10
- [ ] Support P10 MMA acceleration for select libraries
  - [ ] Add github actions to test P10 build flow

**Comment by alexlang74** [comment]
Released!
