### ISSUE TITLE
[FEEDSTOCK REQUEST] tslearn support

### ISSUE THREAD

**Issue by MaximeDeloche** [open-ce/open-ce#593]
**Describe the package you'd like added**

The package is **tslearn** : https://github.com/tslearn-team/tslearn/issues.
It's a popular Python package for time series analysis relying on *numpy*, *scipy* and *scikit-learn*.

**Describe how this package fits in with the project**
I haven't found any conda version for ppc64le and it seems quite used in the domain of machine learning for time series analysis. 

**Additional context**
I tried to install it with `pip install tslearn` ; installation completes but most of the library fails because of `.pyx` files (https://github.com/tslearn-team/tslearn/tree/main/tslearn/metrics) compiled by Cython that results in a segfault on ppc64le when imported. It can be reproduced by importing `tslearn.metrics` (importation of `tslearn` only works fine, but a big part of the library relies on the metrics).

```
(test_env) mdeloche@ /home/mdeloche > python
Python 3.9.7 (default, Sep 16 2021, 16:03:39)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tslearn
>>> import tslearn.metrics
Segmentation fault (core dumped)
(test_env) mdeloche@ /home/mdeloche >
```

Thanks in advance!

**Comment by cdeepali** [comment]
Thanks @MaximeDeloche.

We will see if we can include in OpenCE.

**Comment by alexlang74** [comment]
Hi @MaximeDeloche , can you share evidence regarding tslearn's popularity? The project it self is not very active:
- the last release was in August '21
- there were a very small number of commits in both 2021 and 2022

**Comment by alexlang74** [comment]
will not be pursued
