### ISSUE TITLE
[BUG] [OPEN-CE-ERROR]-14 Build dependencies should form a Directed Acyclic Graph

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce#626]
Hello,

I try to build the open-ce with CUDA 11.2 support for ppc64le and I am getting this error:

[OPEN-CE-ERROR]-14 Build dependencies should form a Directed Acyclic Graph.
The following dependency cycles were detected in the build tree:
libiconv-feedstock -> {'conda-build'} -> {'python-libarchive-c'} -> {'libarchive'} -> {'libxml2'} -> libiconv-feedstock
libiconv-feedstock -> {'conda-build'} -> {'python-libarchive-c'} -> {'libarchive'} -> libiconv-feedstock

Is anyone facing this issue?

**Comment by alexlang74** [comment]
@ticlazau which Open-CE version are you building?

**Comment by ticlazau** [comment]
@alexlang74 Open-CE Builder 9.0.1 for Open-CE v1.6.0

**Comment by cdeepali** [comment]
@ticlazau, please share the command that you use to Build OpenCE packages.

**Comment by cdeepali** [comment]
Identified that this issue is being caused by presence of `conda-forge` in the channels list. 

Because `libxml2` from `conda-forge` depends on libiconv:

```
libxml2 2.9.14 hc8bd4e3_0
-------------------------
file name   : libxml2-2.9.14-hc8bd4e3_0.tar.bz2
name        : libxml2
version     : 2.9.14
build       : hc8bd4e3_0
build number: 0
size        : 935 KB
license     : MIT
subdir      : linux-ppc64le
url         : https://conda.anaconda.org/conda-forge/linux-ppc64le/libxml2-2.9.14-hc8bd4e3_0.tar.bz2
md5         : 939acd4bb692239ef496f9e7ff75af32
timestamp   : 2022-05-02 16:30:00 UTC
dependencies:
  - icu >=70.1,<71.0a0
  - libgcc-ng >=10.3.0
  - libiconv >=1.16,<1.17.0a0
  - libzlib >=1.2.11,<1.3.0a0
  - xz >=5.2.5,<5.3.0a0
  - zlib >=1.2.11,<1.3.0a0
```

However, libxml2 from Anaconda doesn't require libiconv.

**Comment by alexlang74** [comment]
Thanks, @cdeepali ! Is this something we should document, i.e., people should ensure that they don't have conda-forge in their channels list?

**Comment by cdeepali** [comment]
Yes @alexlang74, we can add this into the document.

**Comment by ticlazau** [comment]
Thank you all!
