### ISSUE TITLE
[BUG] openmp fails to build - 

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce#627]
**Describe the bug**
Trying to compile open-ce latest version, I am getting continuous errors with OpenMP:

bld/openmp_1651901885239/work/libomptarget/plugins/cuda/src/../../common/elf_common.c:22:10: fatal error: libelf.h: No such file or directory
 #include <libelf.h>

The libelf.h is existing in the system: libelf: /usr/lib64/libelf.so /usr/include/libelf.h

**To Reproduce**
open-ce build env --python_versions 3.8 ~/open-ce/envs/opence-env.yaml

**Execution Logs**
-- Looking for __atomic_load_1
-- Looking for __atomic_load_1 - not found
-- Looking for __atomic_load_1 in atomic
-- Looking for __atomic_load_1 in atomic - found
-- check-libarcher does nothing.
-- check-openmp does nothing.
-- Configuring done
-- Generating done
-- Build files have been written to: /gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/build
Scanning dependencies of target libomp-needed-headers
Scanning dependencies of target omptarget
Scanning dependencies of target omptarget.rtl.ppc64
Scanning dependencies of target omptarget.rtl.cuda
Scanning dependencies of target archer
Scanning dependencies of target archer_static
[  4%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/omptarget-nvptx_generated_target_impl.cu.o
[  4%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_critical.cu.o
[  6%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_cancel.cu.o
[ 14%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_parallel.cu.o
[ 18%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_sync.cu.o
[ 18%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_data_sharing.cu.o
[ 18%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_omptarget.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_loop.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_task.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_reduction.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_libcall.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_omp_data.cu.o
[ 20%] Building NVCC (Device) object libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/__/common/src/omptarget-nvptx_generated_support.cu.o
[ 23%] Generating kmp_i18n_id.inc
[ 23%] Generating kmp_i18n_default.inc
[ 25%] Building CXX object tools/archer/CMakeFiles/archer_static.dir/ompt-tsan.cpp.o
[ 29%] Building CXX object tools/archer/CMakeFiles/archer.dir/ompt-tsan.cpp.o
[ 31%] Building CXX object libomptarget/src/CMakeFiles/omptarget.dir/rtl.cpp.o
[ 32%] Building CXX object libomptarget/src/CMakeFiles/omptarget.dir/api.cpp.o
[ 34%] Building CXX object libomptarget/src/CMakeFiles/omptarget.dir/interface.cpp.o
[ 34%] Building CXX object libomptarget/src/CMakeFiles/omptarget.dir/omptarget.cpp.o
[ 34%] Building CXX object libomptarget/src/CMakeFiles/omptarget.dir/device.cpp.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 35%] Building CXX object libomptarget/plugins/ppc64le/CMakeFiles/omptarget.rtl.ppc64.dir/__/generic-elf-64bit/src/rtl.cpp.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 37%] Building CXX object libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/src/rtl.cpp.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/libomptarget/plugins/generic-elf-64bit/src/rtl.cpp:18:10: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
          ^~~~~~~
compilation terminated.
make[2]: *** [libomptarget/plugins/ppc64le/CMakeFiles/omptarget.rtl.ppc64.dir/build.make:82: libomptarget/plugins/ppc64le/CMakeFiles/omptarget.rtl.ppc64.dir/__/generic-elf-64bit/src/rtl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:839: libomptarget/plugins/ppc64le/CMakeFiles/omptarget.rtl.ppc64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Built target libomp-needed-headers
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/libomptarget/plugins/cuda/src/rtl.cpp:52:0:
/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/libomptarget/plugins/cuda/src/../../common/elf_common.c:22:10: fatal error: libelf.h: No such file or directory
 #include <libelf.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/build.make:82: libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/src/rtl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:812: libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/all] Error 2
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 39%] Building NVCC intermediate link file libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/omptarget-nvptx_intermediate_link.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target omptarget-nvptx
[ 40%] Linking CXX static library ../../libomptarget-nvptx.a
[ 42%] Linking CXX shared library ../libomptarget.so
[ 42%] Built target omptarget-nvptx
[ 42%] Built target omptarget
[ 45%] Linking CXX static library libarcher_static.a
[ 45%] Linking CXX shared library libarcher.so
[ 45%] Built target archer_static
[ 45%] Built target archer
make: *** [Makefile:149: all] Error 2
Traceback (most recent call last):
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/open_ce/build_feedstock.py", line 167, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 2366, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 1611, in bundle_conda
    utils.check_call_env(interpreter_and_args + [dest_file],
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/gpfs/home/s4s004/coredump/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/usr/bin/bash', '-e', '/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/build-llvm-openmp.sh']' returned non-zero exit status 2.
[OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
Command '['/usr/bin/bash', '-e', '/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/build-llvm-openmp.sh']' returned non-zero exit status 2.
ERROR:OPEN-CE:[OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
Command '['/usr/bin/bash', '-e', '/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/build-llvm-openmp.sh']' returned non-zero exit status 2.
ERROR OPEN-CE:<module>(139): [OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: openmp-feedstock
Command '['/usr/bin/bash', '-e', '/gpfs/home/s4s004/coredump/anaconda3/envs/opence/conda-bld/openmp_1651901885239/work/build-llvm-openmp.sh']' returned non-zero exit status 2.

**Comment by cdeepali** [comment]
I will check this.

**Comment by alexlang74** [comment]
Closing as done.
