### ISSUE TITLE
Update documentation for removal of cudatoolkit-dev

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#68]
Update the documentation to mention that it is required for CUDA to be installed for native builds outside of a container. This version will need to match the version of cudatoolkit passed to builds (so far only 10.2 is supported).

We should also remove any mentions of using the PowerAI channel from documentation that might exist.

**Comment by npanpaliya** [comment]
This is covered under https://github.com/open-ce/open-ce/pull/73. I don't find any other place where cudatoolkit-dev or PowerAI's public channel is referred in the docs.

**Comment by bnemanich** [comment]
We still need to mention that for CUDA builds, the CUDA development tools need to be installed. We should provide a link to where to download them.

We also need to mention that CUDA_HOME needs to be set.
