### ISSUE TITLE
Clang compiling failed using latest opence 1.7.1 [BUG] 

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce#685]
Hello,

I am trying to compile lated opence 1.7.1 on ppc64le and is failing on clang (see below output). This issue is for CUDA 11.2 as well as 11.4
Any advice?

`
## Package Plan ##

  environment location: /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla

The following NEW packages will be INSTALLED:

    _libgcc_mutex:               0.1-main
    binutils_impl_linux-ppc64le: 2.33.1-he6710b0_7
    binutils_linux-ppc64le:      2.33.1-h959c939_15
    clang:                       13.0.1-hcedea39_0         file:///root/condabuild
    clang-13:                    13.0.1-default_h6a5c632_0 file:///root/condabuild
    clangxx:                     13.0.1-default_he4ea32b_0 file:///root/condabuild
    gcc_impl_linux-ppc64le:      8.2.0-he01c8ba_1
    gcc_linux-ppc64le:           8.2.0-h9f3bcec_15
    gxx_impl_linux-ppc64le:      8.2.0-h822a55f_1
    gxx_linux-ppc64le:           8.2.0-h9f3bcec_15
    ld_impl_linux-ppc64le:       2.33.1-h0f24833_7
    libclang-cpp13:              13.0.1-default_h6a5c632_0 file:///root/condabuild
    libgcc-ng:                   8.2.0-h822a55f_1
    libgfortran-ng:              7.3.0-h822a55f_1
    libllvm13:                   13.0.1-h3cc6e9e_0         file:///root/condabuild
    libstdcxx-ng:                8.2.0-h822a55f_1
    zlib:                        1.2.12-h140841e_2

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ clang++ --version
+ clang++ -v -c mytest.cxx
clang version 13.0.1
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin
Found candidate GCC installation: /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0
Selected GCC installation: /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-11.2, version 11.2
 (in-process)
 "/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/clang-13" -cc1 -triple powerpc64le-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name mytest.cxx -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu ppc64le -mfloat-abi hard -target-abi elfv2 -debugger-tuning=gdb -v -fcoverage-compilation-dir=/opt/conda/conda-bld/clang_packages_1662310410835/test_tmp -resource-dir /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/clang/13.0.1 -isysroot /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0 -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/powerpc64le-conda_cos7-linux-gnu -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/backward -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/clang/13.0.1/include/ppc_wrappers -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/clang/13.0.1/include -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/local/include -internal-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include -internal-externc-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/include -internal-externc-isystem /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/include -fdeprecated-macro -fdebug-compilation-dir=/opt/conda/conda-bld/clang_packages_1662310410835/test_tmp -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o mytest.o -x c++ mytest.cxx
clang -cc1 version 13.0.1 based upon LLVM 13.0.1 default target powerpc64le-unknown-linux-gnu
ignoring nonexistent directory "/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/local/include"
ignoring nonexistent directory "/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/powerpc64le-conda_cos7-linux-gnu
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/backward
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/clang/13.0.1/include/ppc_wrappers
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/clang/13.0.1/include
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include
 /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/include
End of search list.
In file included from mytest.cxx:1:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/iostream:39:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/ostream:38:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/ios:39:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/exception:144:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/nested_exception.h:40:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/move.h:55:
/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/type_traits:335:39: error: __float128 is not supported on this target
    struct __is_floating_point_helper<__float128>
                                      ^
In file included from mytest.cxx:1:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/iostream:39:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/ostream:38:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/ios:42:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/ios_base.h:41:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/locale_classes.h:40:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/string:52:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/basic_string.h:6391:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/ext/string_conversions.h:41:
In file included from /opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/cstdlib:77:
/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/std_abs.h:102:7: error: __float128 is not supported on this target
  abs(__float128 __x)
      ^
/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/include/c++/8.2.0/bits/std_abs.h:101:3: error: __float128 is not supported on this target
  __float128
  ^
3 errors generated.
Tests failed for clangxx-13.0.1-default_he4ea32b_0.conda - moving package to /opt/conda/conda-bld/broken
WARNING:conda_build.build:Tests failed for clangxx-13.0.1-default_he4ea32b_0.conda - moving package to /opt/conda/conda-bld/broken
export PREFIX=/opt/conda/conda-bld/clang_packages_1662310410835/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export SRC_DIR=/opt/conda/conda-bld/clang_packages_1662310410835/test_tmp
INFO: activate-binutils_linux-ppc64le.sh made the following environmental changes:
+ADDR2LINE=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-addr2line
+AR=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-ar
+AS=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-as
+CXXFILT=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-c++filt
+ELFEDIT=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-elfedit
+GPROF=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gprof
+HOST=powerpc64le-conda_cos7-linux-gnu
+LD=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-ld
+NM=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-nm
+OBJCOPY=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-objcopy
+OBJDUMP=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-objdump
+RANLIB=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-ranlib
+READELF=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-readelf
+SIZE=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-size
+STRINGS=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-strings
+STRIP=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-strip
INFO: activate-gcc_linux-ppc64le.sh made the following environmental changes:
+CC=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc
+CFLAGS=-mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clangxx-13.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_PREFIX_PATH=$PREFIX:$PREFIX/powerpc64le-conda_cos7-linux-gnu/sysroot/usr
+CONDA_BUILD_SYSROOT=$PREFIX/powerpc64le-conda_cos7-linux-gnu/sysroot
+CPP=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cpp
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+DEBUG_CFLAGS=-mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clangxx-13.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+GCC=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc
+GCC_AR=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-ar
+GCC_NM=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-nm
+GCC_RANLIB=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_powerpc64le_conda_cos7_linux_gnu
INFO: activate-gxx_linux-ppc64le.sh made the following environmental changes:
+CXX=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-c++
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clangxx-13.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clangxx-13.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+GXX=$PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-g++
clang version 13.0.1
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: $PREFIX/bin
TESTS FAILED: clangxx-13.0.1-default_he4ea32b_0.conda
WARN[0010] StopSignal SIGTERM failed to stop container open-ce-builder-20220904123606 in 10 seconds, resorting to SIGKILL
open-ce-builder-20220904123606
[OPEN-CE-ERROR]-4 Error executing build in container: "open-ce-builder-20220904123606"
`

**Comment by cdeepali** [comment]
I will check this locally and get back to you.

**Comment by ticlazau** [comment]
Thank you @cdeepali

**Comment by cdeepali** [comment]
This issue is fixed by commit - https://github.com/open-ce/open-ce/commit/4bdcf9b5432068aa0cd5c02f98969121a15c55a6.
