### ISSUE TITLE
Pytorch 1.6 build error

### ISSUE THREAD

**Issue by dustinvanstee** [open-ce/open-ce#7]
Hello, I forked the repository and ran the following command to try and build a pytorch 1.6 release on a power8 minsky server ...

python build_env.py ../envs/pytorch-env.yaml

Here was the error I had currently.

ERROR: local_src_dir path "/gpfs/home/s4s004/vanstee/2020-09-opence/open-ce/builder/tensorrt-feedstock/config/../../local_files" specified doesn't exist
Unable to build recipe: tensorrt-feedstock

Also, once this process completes, how would I conda install the build into a virtual environment that I have ?  Does it make *whl files or something like that?

**Comment by bnemanich** [comment]
Hi, 

The TensorRT repo requires a manual download of the TensorRT packages from Nvidia's website. For more details, please see: https://github.com/open-ce/tensorrt-feedstock. You should create a new directory called `local_files` within the directory where you will be running the build_env script from. The TensorRT tar file should go within this directory.

The output of the build_env script will be a conda channel (by default it will be called `condabuild`). You can install packages from this channel into your current conda environment by running `conda install -c ./condabuild PACKAGE_NAME`.

**Comment by bnemanich** [comment]
Just added some new documentation with some of this information (#8). The main README.md will have those changes. Please follow those instructions and let us know how it goes.

**Comment by jayfurmanek** [comment]
Closing this one. Please reopen if you find the documentation unclear.

**Comment by dustinvanstee** [comment]
Hi thanks for the updates.  Here is an update : so I downloaded the tensorrt archive (both TensorRT-7.0.0.11.CentOS-7.6.ppc64le-gnu.cuda-10.2.cudnn7.6.tar.gz and TensorRT-7.2.0.13.CentOS-8.1.ppc64le-gnu.cuda-11.0.cudnn8.0.tar.gz).  I then created a directory called local_files in my build director and place the archives in the local_files directory.  

Next i ran this command
python build_env.py --python_versions 3.7  --conda_build_config ../conda_build_config.yaml     ../envs/opence-env.yaml

I still get this error 
```
Failure building recipe: tensorrt
Unable to build recipe: tensorrt-feedstock
```

My system is a power9 with Rhel 8, and CUDA 11.0.   Should i be modifying the defaults to run this on my system config below ?  

kernel : 4.18.0-147.20.1.el8_1.ppc64le
 
NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0

(base) [vanstee@p10a04 2020-09-opence]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_May__6_19:09:32_PDT_2020
Cuda compilation tools, release 11.0, V11.0.167
Build cuda_11.0_bu.TC445_37.28358933_0

**Comment by jayfurmanek** [comment]
Looks like you did find an issue with the TRT recipe:
https://github.com/open-ce/tensorrt-feedstock/issues/2

Note that Open-CE doesn't support RH8 CUDA11 yet. We plan for an initial release on RH7, CUDA10.2, then move to RH8 next.

**Comment by dustinvanstee** [comment]
So I ended up getting a system with RHEL 7.6 and Cuda 10.2 and tried to build using a machine of that type.  I got past the tensorrt issue, but hit a problem a little later in the workflow.  

```
Traceback (most recent call last):
  File "/gpfs/home/s4s004/vanstee/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/gpfs/home/s4s004/vanstee/anaconda3/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/gpfs/home/s4s004/vanstee/anaconda3/conda-bld/pytorch-base_1599922693474/work/conda_build.sh']' returned non-zero exit status 1.
Builds for python version: 3.7

```
...

```
Failure building recipe: pytorch-base
Unable to build recipe: pytorch-feedstock
```

System Details
Linux p10a114 3.10.0-957.21.3.el7.ppc64le #1 SMP Fri Jun 14 06:58:05 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

vanstee@p10a114:~/2020-09-opence/power8rhel76cuda10.2 $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Thu_Oct_24_17:58:26_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

 NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2

Attaching build log as well
[opence.log](https://github.com/open-ce/open-ce/files/5214073/opence.log)

**Comment by jayfurmanek** [comment]
We've not seen these errors before. We'll take a look. In the meantime can you try building the container located at `https://github.com/open-ce/open-ce/tree/master/ci_common_scripts/base` and then doing the build there?

**Comment by jayfurmanek** [comment]
It looks like that since you have lmdb-devel and openblas installed locally, the pytorch build is grabbing the local ones. It shouldn't do that.
For you now if you build in the container above (which is ubi7 based, so very minimal) or remove lmdb-devel, openblas from local that should get around the issue.

**Comment by bnemanich** [comment]
@dustinvanstee we added a new flag to the `build_env` script that will automatically perform the build inside of docker container. If you have a chance, please try using the `--docker_build` option and see if this resolves your problems. Please see https://github.com/open-ce/open-ce#building-within-a-docker-container for more information.

**Comment by bnemanich** [comment]
Closing this issue. The `--docker_build` option was added to the open-ce tools to allow for builds within a container.

open-ce/pytorch-feedstock#13 and open-ce/pytorch-feedstock#14 should address system libraries being picked up ahead of ones within the current conda environment.

**Comment by jplij** [comment]
> We plan for an initial release on RH7, C

Hi, does open-ce now support RH8? Our server use RH8 so one has to stick to that. Thanks in advance!

**Comment by jayfurmanek** [comment]
Hi @jplij 

For questions like this, a better place to ask would be the community Slack channel. You can find a link to get an invite on the main README.

To answer your question, though, yes. Open-CE 1.1 now can build on and run on RH8 (x86_64, ppc64le). Note that in some cases we assume CUDA11 on RH8.
