### ISSUE TITLE
[FEEDSTOCK REQUEST] Forecasting time series packages/dependencies to be included in a future open-ce release

### ISSUE THREAD

**Issue by harmojd** [open-ce/open-ce#705]
Open-CE Team,

My name is Jesse Harmon and I collaborating with the POWER enablement and optimization team.

We are requesting the following forecasting time series packages/dependencies to be included in a future open-ce release:
numpy
pandas
prophet (https://facebook.github.io/prophet)
orbit-ml (https://github.com/uber/orbit)
cmdstan
pystan
cmdstanpy

Thanks for all your help,
Jesse

**Comment by alexlang74** [comment]
Hi @harmojd , thanks for reaching out! 
We will check whether we can include the following libraries in our OpenCE 1.8 release stream, which we're currently working on:

- prophet 
- orbit-ml 
- cmdstan
- pystan
- cmdstanpy

The following libraries are provided by Anaconda for Power. That's why we don't include them into OpenCE:
- pandas
- numpy

We will of course ensure that above time series libs work with the pandas / numpy versions from Anaconda.

**Comment by harmojd** [comment]
Alexander,

Thanks for your help!  We really appreciate it!

After meeting/collaborating with the POWER enablement and optimization team
we discussed that numpy/pandas from Anaconda are not optimized for POWER.

Dillard's is using packages from https://urldefense.com/v3/__https://anaconda.org/rocketce__;!!IoaeSlivZg!w3Q4pNXtFfMGkeh0Lhu4Vy_lTmR_TFiUUqFI1YX_lRwxi80tME8jRfXxeAZJdTyXfXDVNUzJhgwtHCfDan5MFa5MwiSh1Qxv35tptKyZ4aUnGcGBg_c-xMYwO7olFh9LQGFF3g$   and we
thought by adding these packages into OpenCE this would make it easier for
the RocketCE team to optimize these packages from a CI/CD perspective.

Thanks for your help,
Jesse and Lenin

**Comment by alexlang74** [comment]
Hi @harmojd , 

a quick update: as `numpy` will also benefit from MMA optimizations on P10, we will try to include it in OpenCE as well.

**Comment by harmojd** [comment]
Alexander,

Awesome!  This is great news!

Thank you so much,
Jesse

**Comment by harmojd** [comment]
Alexander,

We are looking at other frameworks that can benefit from Power10
optimizations like around OpenBLAS.

We are already using PuLP(https://urldefense.com/v3/__https://anaconda.org/conda-forge/pulp__;!!IoaeSlivZg!zsdp_nAZTvpwjpOdPMEjodr1IdTQghhq2CBJRlhdXbK5xmEQ18aYojKiJiZNYlCUKEf6nk2AFg-L9Norvngqnfh3mlUokhX7sXblQRnaaQmTn6-3Ic6p2rpLkcHJHtSbReZPW3ZH$  ) but we are
needing the ability to use the Clp solver.

Is it possible to have this framework added to OpenCE?

https://urldefense.com/v3/__https://github.com/google/or-tools__;!!IoaeSlivZg!zsdp_nAZTvpwjpOdPMEjodr1IdTQghhq2CBJRlhdXbK5xmEQ18aYojKiJiZNYlCUKEf6nk2AFg-L9Norvngqnfh3mlUokhX7sXblQRnaaQmTn6-3Ic6p2rpLkcHJHtSbRRoFkNw5$  

Google Operations Research Tools (or-tools) python package
https://urldefense.com/v3/__https://anaconda.org/conda-forge/ortools-python__;!!IoaeSlivZg!zsdp_nAZTvpwjpOdPMEjodr1IdTQghhq2CBJRlhdXbK5xmEQ18aYojKiJiZNYlCUKEf6nk2AFg-L9Norvngqnfh3mlUokhX7sXblQRnaaQmTn6-3Ic6p2rpLkcHJHtSbRXtGb7eV$  

Thanks,
Jesse and Lenin

**Comment by alexlang74** [comment]
Hi @harmojd , 

quick update: we're on track to deliver the following packages in OpenCE 1.8 in Q4:
- prophet
- orbit-ml
- cmdstan
- cmdstanpy

We found `pystan` to be available in Anaconda default channel. This is why we don't build the package in OpenCE. 

You can track our progress in  https://github.com/open-ce/open-ce/issues/706

**Comment by alexlang74** [comment]
Hi @harmojd ,

on your other request (sorry for the late response): you'd like us to include `or-tools`, correct? Because you can use `pulp` from Anaconda...

**Comment by harmojd** [comment]
Alexander,

This is great news!  Thank you!

It would be awesome if you all could include Google's or-tools optimization
package to complement the other forecasting time series packages you will
add in OpenCE 1.8.

Thank you for your help,
Jesse

**Comment by alexlang74** [comment]
Ok. I won't promise anything now, but will check with the team tomorrow...

**Comment by alexlang74** [comment]
Hi @harmojd ,

we'll need more time to integrate `or-tools`. We're now starting the release build for OpenCE 1.8. Once 1.8 is released (tentatively next week from our end), we will pick up the work for `or-tools?`to include it in 1.8.1...

**Comment by harmojd** [comment]
Alexander,

Thank you for the update!  We really appreciate all your help.

Thanks,
Jesse and Lenin
