### ISSUE TITLE
[QUESTION] How do I convince conda to install my open-ce packages?

### ISSUE THREAD

**Issue by adammoody** [open-ce/open-ce#708]
After building packages with ``open-ce build env``, I have trouble getting conda to select those packages for installation.  For example, with pytorch, I see the following:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |         openblas           9 KB  file:///path/to/opence-1.5.5/condabuild
    future-0.18.2              |           py38_1         642 KB
    libgfortran-ng-7.3.0       |       h822a55f_1         1.0 MB
    libopenblas-0.3.18         |       hdbe1a1d_1         5.2 MB  file:///path/to/opence-1.5.5/condabuild
    ninja-1.10.2               |       h6ffa863_5           8 KB
    ninja-base-1.10.2          |       h66086b3_5         124 KB
    numpy-1.21.5               |   py38h76732f4_2          24 KB
    numpy-base-1.21.5          |   py38h37faa36_2         4.9 MB
    pytorch-1.10.2             |cpu_py38h6f0ae12_0        39.3 MB
    typing-extensions-4.3.0    |   py38h6ffa863_0           8 KB
    typing_extensions-4.3.0    |   py38h6ffa863_0          41 KB
    ------------------------------------------------------------
                                           Total:        51.2 MB
```
Above, conda wants to install the CPU-only pytorch package from anaconda instead of the CUDA-enabled pytorch from my local conda channel from my open-ce build.  Though, conda *does* select some packages from my local conda channel, like ``blas``.

I can see that it finds the local pytorch with a ``conda search pytorch`` command.
```
conda search pytorch
Loading channels: done
# Name                       Version           Build  Channel             
pytorch                       1.10.2 cpu_py310hef0c51e_0  pkgs/main           
pytorch                       1.10.2 cpu_py37h6f0ae12_0  pkgs/main           
pytorch                       1.10.2 cpu_py38h6f0ae12_0  pkgs/main           
pytorch                       1.10.2 cpu_py39h6f0ae12_0  pkgs/main           
pytorch                       1.10.2 cuda10.2_py38_1  condabuild     
```

However, conda must believe that package is incompatible with my environment for some reason and skips it.

I can also see that the opence pytorch from my local conda channel *is* installed when I build other opence packages, like horovod:
```
The following NEW packages will be INSTALLED:

    _libgcc_mutex:                0.1-main
    _openmp_mutex:                5.1-1_gnu
    _pytorch_select:              2.0-cuda_2                             file:///path/to/opence-1.5.5/condabuild
    _tensorflow_select:           2.0-cuda_2                             file:///path/to/opence-1.5.5/condabuild
    absl-py:                      0.12.0-py38h6ffa863_0
    aiohttp:                      3.8.1-py38h140841e_1
<snip>
    pytorch:                      1.10.2-cuda10.2_py38_1                 file:///path/to/opence-1.5.5/condabuild
    pytorch-base:                 1.10.2-h1234567_cuda10.2_py38_pb3.19_5 file:///path/to/opence-1.5.5/condabuild
    pytz:                         2022.1-py38h6ffa863_0
```

Do you have any suggestions on what I must be missing from my conda environment?

Thanks.

**Comment by cdeepali** [comment]
@adammoody, please try `--strict-channel-priority` along with install command like:
`conda install --strict-channel-priority pytorch`.

Another alternative is to specify the desired pytorch version while installing it in the conda environment to force conda to use the package from OpenCE instead of pulling it from defaults channel like.
`conda install pytorch=1.10.2=cuda10.2_py38_1`.

**Comment by adammoody** [comment]
Thank you for the suggestions, @cdeepali .

The ``--strict-channel-priority`` option fails and prints a bunch of conflict messages.  There are so many it's difficult to see how to resolve things.

However, using the more specific name for pytorch worked ``conda install pytorch=1.10.2=cuda10.2_py38_1``.
```
   pytorch-1.10.2             |  cuda10.2_py38_1           4 KB  file:///path/to/condabuild
   pytorch-base-1.10.2        |h1234567_cuda10.2_py38_pb3.19_5       345.3 MB  file:///path/to/opence-1.5.5/condabuild
```
That also printed some packages that were changed in the process, so maybe those were the culprits contributing to the conflicts in the other ways I tried preventing a simple ``conda install pytorch`` from working:
```
The following packages will be SUPERSEDED by a higher-priority channel:

  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1~ --> pkgs/main/linux-ppc64le::six-1.15.0-py38h6ffa863_0

The following packages will be DOWNGRADED:

  cffi                                1.15.1-py38h50e77d8_0 --> 1.14.6-py38hf9d8e4b_0
  pyyaml                                 6.0-py38h140841e_1 --> 5.4.1-py38h140841e_1
```

Assuming we need to similarly use the more specific names for other packages in the release, is there a good way to get the full list?

I could write a script to extract the "name", "version", and "build" fields from the ``condabuild/linux-ppc64le/repodata.json`` and ``condabuild/noarch/repodata.json" files.  Would that be sufficient?  Or is there a better way?

Thanks.

**Comment by adammoody** [comment]
If there's not a more direct way, this script generates the full package names:
```
import os
import json

pkgs = []
for subdir in ['noarch', 'linux-ppc64le']:
  fname = os.path.join('condabuild', subdir, 'repodata.json')
  with open(fname) as f:
    repodata = json.load(f)
    for p in repodata['packages']:
      vals = [repodata['packages'][p][field] for field in ['name', 'version', 'build']]
      pkgs.append("=".join(vals))

for p in sorted(pkgs):
  print p
```

**Comment by npanpaliya** [comment]
@adammoody - How about parsing the output of `conda search pytorch -c file:///path/to/opence-1.5.5/condabuild`? This gives output in following format - 
```
(base) [npanpa23@dlw01 ~]$ conda search pytorch -c http://ausgsa.ibm.com/projects/o/open-ce/conda/open-ce-r1.5.5/
Loading channels: done
# Name                       Version           Build  Channel
pytorch                       1.10.2 cpu_py310hef0c51e_0  pkgs/main
pytorch                       1.10.2 cpu_py37h6f0ae12_0  pkgs/main
pytorch                       1.10.2 cpu_py38h6f0ae12_0  pkgs/main
pytorch                       1.10.2 cpu_py39h6f0ae12_0  pkgs/main
pytorch                       1.10.2 cuda11.2_py38_1  projects/o/open-ce/conda/open-ce-r1.5.5
pytorch                       1.10.2 cuda11.2_py39_1  projects/o/open-ce/conda/open-ce-r1.5.5
```

**Comment by cdeepali** [comment]
@adammoody, the `opence build env` command generates conda environment files under the output directory for each variant. 
For eg, in case of a `py38 cuda 11.2` build you would get a file with name `opence-conda-env-py3.8-cuda-openmpi-11.2.yaml` under output folder (`/path/to/opence-1.5.5/condabuild`). This file has details of all the packages needed and can be used to create an environment using the command:
`conda env create -f opence-conda-env-py3.8-cuda-openmpi-11.2.yaml`.  

More details at - https://github.com/open-ce/open-ce-builder/blob/main/doc/README.open_ce_build.md#conda-environment-files

**Comment by adammoody** [comment]
Thanks for the suggestions, @npanpaliya and @cdeepali .  I did consider the conda search output before settling on just parsing the json file.  The environment file sounds like a clean option for our users.

Not all packages build for me yet, so I have been building environments one-by-one, e.g., tensorflow-env, then python-env.  I am saving all conda packages to the same condabuild directory.  It looks like each of those package builds overwrites the environment file of the previous build (``opence-conda-env-py3.8-cuda-system-10.2.yaml``), so I only end up with a single environment file that corresponds to the most recent package build.

However, the documentation suggests that I can recreate those environment files without having to rebuild packages using ``--skip_build_packages``.  From there, I suspect I could either rename the files or merge their contents into one single file for all packages.

**Comment by cdeepali** [comment]
@adammoody, you may update the https://github.com/open-ce/open-ce/blob/main/envs/opence-env.yaml locally to contain only the envs that you want to build  in the `imported_envs` section - https://github.com/open-ce/open-ce/blob/main/envs/opence-env.yaml#L4-L19.  You can remove all not needed envs listed there. 

Then use `build env` command to build this modified `opence-env.yaml` to get a output conda environment file which would contain all packages that you are interested in. ( If the packages are already present in the output directory, these would by default not get rebuilt)

**Comment by alexlang74** [comment]
@adammoody - did this solve your question?
