### ISSUE TITLE
[QUESTION] CMake Error: protobuf cannot be found

### ISSUE THREAD

**Issue by kkly1995** [open-ce/open-ce#716]
I am trying to build [this](https://github.com/mir-group/pair_nequip) on a ppc64le machine, which integrates torch models into the simulation software LAMMPS (c++). I realize this is perhaps not the place to ask about LAMMPS, but since the error message specifies the torch configuration, I hope there's a chance that I could get some help.

Attempting the build with open-ce 1.5.1, 1.6.1, and 1.7.2 all lead to the same error:
```
CMake Warning at /opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/site-packages/torch/share/cmake/Caffe2/public/protobuf.cmake:88 (message):
  Protobuf cannot be found.  Depending on whether you are building Caffe2 or
  a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:56 (include)
  /opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:922 (find_package)


CMake Error at /opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:58 (message):
  Your installed Caffe2 version uses protobuf but the protobuf library cannot
  be found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH? If you do not have protobuf, you will need to install
  protobuf and set the library path accordingly.
Call Stack (most recent call first):
  /opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:922 (find_package)


-- Configuring incomplete, errors occurred!
```

This is confusing since protobuf actually does exist:
```
$ conda list | grep protobuf
libprotobuf               3.19.4               h690f14c_0    conda-forge
protobuf                  3.19.4           py39had50986_0    conda-forge
```

What are the appropriate library paths to set?

[edit] an example from scratch:
```
git clone -b stable https://github.com/lammps/lammps.git test_lammps
git clone https://github.com/mir-group/pair_nequip.git
cd pair_nequip/
./patch_lammps.sh ../test_lammps/
cd ../test_lammps/
mkdir build
cd build/
cmake ../cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`
```

**Comment by cdeepali** [comment]
Please share the steps that you are using to build the `pair_nequip` package alongside OpenCE.

**Comment by kkly1995** [comment]
I've updated the question with some steps to try and reproduce

**Comment by cdeepali** [comment]
Thanks @kkly1995. I will try with these.

**Comment by cdeepali** [comment]
Could you please install `protobuf` from Anaconda's default channel instead of pulling it from `conda-forge` and retry the build. 
Also please share output of `conda list` from your build environment.

**Comment by npanpaliya** [comment]
Our packages in Open-CE 1.6.1 are built with protobuf 3.19. So, conflicts when packages are installed along with protobuf 3.9 are expected.

**Comment by cdeepali** [comment]
The following works for me:

```
conda create -y -n dctest_lammps
conda activate dctest_lammps
conda install -c https://ftp.osuosl.org/pub/open-ce/1.6.1/ pytorch=1.10.2=cuda11.2_py38_1 protobuf python=3.8 cmake gxx_linux-ppc64le

git clone -b stable https://github.com/lammps/lammps.git test_lammps
git clone https://github.com/mir-group/pair_nequip.git
cd pair_nequip/
./patch_lammps.sh ../test_lammps/
cd ../test_lammps/
mkdir build
cd build/
cmake ../cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`
```

```
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.19.1
```

Are you building the package on baremetal or container?

**Comment by kkly1995** [comment]
I am building on bare. It looks like using conda's `cmake` is what makes the difference. How come this is necessary here, but not so in environment with the CPU version?

**Comment by cdeepali** [comment]
Ideally, `cmake` should be installed in the conda environment for both use cases. Perhaps you also have `cmake` installed on your system?

**Comment by alexlang74** [comment]
@kkly1995 Is there anything left for us to help you with?

**Comment by alexlang74** [comment]
Please reopen if something is still not working
