### ISSUE TITLE
[FEEDSTOCK REQUEST] Making `rdkit` compatible with latest versions of `open-ce`

### ISSUE THREAD

**Issue by amorehead** [open-ce/open-ce#725]
**Describe the package you'd like added**
Making RDKit compatible with latest versions of `open-ce`.

**Additional context**
Currently, I am running a command such as `conda create --prefix my-env/ --clone open-ce-1.5.2-py38-0` to create new Conda environment based on a version of `open-ce`. After that, I have tried installing a Conda package called `rdkit` using the command `conda install -c conda-forge rdkit` inside this new environment. However, the dependencies required for `rdkit` never seem to resolve with respect to those of `open-ce`.

For reference, I am currently running that above commands on an IBM Power9/PowerPC compute cluster (i.e., Oak Ridge National Lab's Summit compute server).

**Comment by npanpaliya** [comment]
Using packages from conda-forge are not guaranteed to work with open-ce packages.

**Comment by npanpaliya** [comment]
One way is to build conda-forge's rdkit recipe by using open-ce tools (open-ce-builder, to be specific `open-ce build feedstock` command), but you would need to pin the dependencies of rdkit to what we have in our [conda_build_config.yaml](https://github.com/open-ce/open-ce/blob/open-ce-v1.5.2/envs/conda_build_config.yaml).

**Comment by amorehead** [comment]
I found a way of getting around this issue for now, by installing `open-ce` packages after I have installed `rdkit` using `conda-forge`. Thank you for suggesting this alternative approach to me. I'll consider it for future scenarios.
