### ISSUE TITLE
[FEEDSTOCK REQUEST] CatBoost

### ISSUE THREAD

**Issue by Kennric** [open-ce/open-ce#726]
**Describe the package you'd like added**
We would like to add the  Catboost package to OpenCE. From the Catboost page: (https://catboost.ai)

CatBoost is a high-performance open source library for gradient boosting on decision trees

**Describe how this package fits in with the project**

This package has been requested by an OpenCE user at NYU, it is a popular and widely used gradient boosting library.

**Additional context**

CatBoost paper on arxiv: https://arxiv.org/abs/1706.09516

* It's not provided in Anaconda's default channel
* There's no ppc version on conda_forge
* It's an active project with a quick release cycle.

**Comment by alexlang74** [comment]
Thank you, @Kennric ! We will look into the package as part of the next OpenCE 1.8 fix pack..

**Comment by cdeepali** [comment]
@Kennric, we would not be able to build _CatBoost_ as part of OpenCE because it uses a closed source build system.
