### ISSUE TITLE
[QUESTION] How to upgrade pytorch, torchvision (and transformers)

### ISSUE THREAD

**Issue by asmith26** [open-ce/open-ce#727]
Hi there, 

Thanks for this fantastic utility for installing common machine/deep learning packages on Power9 systems with GPU support. I had been struggling for quite a while before I came across your repo.

Just wondering how do I upgrade some versions of the libraries? I'm installing my required packages with:

```bash
$ mamba install -c https://ftp.osuosl.org/pub/open-ce/current/ pytorch torchvision transformers
```

but I notice some of the libs are not on the latest versions:

- pytorch: I get **v1.3.1**, latest is [v1.13.0](https://pytorch.org/)
- torchvision: I get **v0.4.2**, latest is [v0.14](https://pytorch.org/vision/versions.html)
- transformers: I get **v4.24.0**, latest is [v4.24.0](https://huggingface.co/docs/transformers/index)

Many thanks for any help! :)

**Comment by npanpaliya** [comment]
@asmith26 - We are working on a new Open-CE release 1.8 which will update the libraries to their latest released version. You can check the contents of Open-CE 1.8 here https://github.com/open-ce/open-ce/issues/706. Once this is released, and OSU builds it, you will get the latest libraries.

**Comment by asmith26** [comment]
Hi @npanpaliya, thanks very much for your information and help. It looks like that PR has now been merged, but I seem to be still getting the older versions (possible the new package(s) need to be deployed/published?) 
Thanks again!

**Comment by npanpaliya** [comment]
Yes, Open-CE 1.8 is about to be released in next 2-3 days. But the availability of the latest packages depend on when OSU will build them.

**Comment by alexlang74** [comment]
OpenCE 1.8 has been released. Given the upcoming Christmas season, I can't tell when OSU will be able to build the packages, though...

**Comment by asmith26** [comment]
> OpenCE 1.8 has been released. Given the upcoming Christmas season, I can't tell when OSU will be able to build the packages, though...

Thanks very much for your help & info - just thought I'd check, is there any way that I can build the packages locally?

**Comment by alexlang74** [comment]
Hi @asmith26 , 
yes, you can also build packages locally. See https://github.com/open-ce/open-ce-builder. . If anything is unclear, let us know!
