### ISSUE TITLE
OpenCE v1.8.1 Release contents

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#742]
- [x] xgboost ~~1.7.2~~ 1.7.3
- [x] PyTorch 1.13.1
- [x] DeepSpeed v0.7.7
- [x] PyTorch Geometric v2.2.0
- [x] PyTorch Lightning ~~1.8.4~~ 1.8.6 and Lightning app.
- [x] SnapML 1.11.1
- [x] LightGBM 3.3.4
- [x] Beam 2.43.0
- [x] or-tools v9.2 https://github.com/open-ce/open-ce/issues/741
- ~[ ] catboost (if possible)~ Not possible to build on ppc
- [x] DALI 1.21
- [x] Tensorflow metadata 1.12.0
- [x] Tensorflow Datasets 4.8.2
- [ ] ~ONNX 1.13~  — not  possible as pytorch 1.13 still uses onnx 1.12
- [x] Ray 2.2   --> may come post 1.8.1
- [ ] RAPIDS  --> post 1.8.1
- [x] Mamba 1.1.0
- [ ] Revisit PyTorch memory issue with tensor size, using latest PyTorch --> post 1.8.1
- [x] Deepspeed Feedstock tests
- [x] Investigate numpy performance issues reported by RocketCE team and by community
- [x] Stop building mpi and llvmdev packages for s390x as these are available on Anaconda. 
- [x] Stop building zlib for s390x as it is available on Anaconda.
- [x] Build onnx for s390x
- [x] pip check failures from v1.8.0 - https://github.com/open-ce/open-ce/issues/739
- [x] Build sklearn-pandas on ppc and x86 (port from 1.7 branch)
- [x] Update setuptools pin to 65.* (setuptools remains at 63.* for P10 builds)

**Comment by alexlang74** [comment]
done
