### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by eric-aquaronne** [open-ce/open-ce#745]
**Your question:**
You need to ADD mention RocketCE in your main documentation as this is the IBM recommended source for binaries of OpenCE and  supported for POWER machines  (see RocketCE conda download channel, and their support web site https://community.rocketsoftware.com/forums/power?CommunityKey=c7ece6e8-5a29-4a17-a2bc-68b65f89d29f)

![image](https://user-images.githubusercontent.com/29255875/209152702-fafb130d-f448-4a2c-a923-a4451dfeaeab.png)

**Comment by cdeepali** [comment]
Sure Eric, we will add RocketCE in the documentation.
