### ISSUE TITLE
[FEEDSTOCK REQUEST] Optimized Python to be added to OpenCE

### ISSUE THREAD

**Issue by harmojd** [open-ce/open-ce#754]
OpenCE Team,

I have worked the last few months with Calvin Sze on creating an optimized Python for the ppc64le platform.

It would be great if the OpenCE project could incorporate an optimized Python for the ppc64le platform.

Thanks,
Jesse

**Comment by alexlang74** [comment]
Hi @harmojd ,
we've started on this task (we've already created a https://github.com/open-ce/python-feedstock with teh necessary build commands). Will keep you posted...

**Comment by harmojd** [comment]
Alexander,

This is great news!  Thank you for your help!

Thanks,
Jesse

**Comment by alexlang74** [comment]
Done!-) https://github.com/open-ce/open-ce-python/releases/tag/open-ce-python-v1.0.0
