### ISSUE TITLE
OpenCE 1.9 release contents

### ISSUE THREAD

**Issue by alexlang74** [open-ce/open-ce#765]
## Python versions

- Python 3.8
- Python 3.9
- Python 3.10

## CUDA versions

- CUDA 11.2 (for compatibility with TensorFlow)
- CUDA 11.8 
- CUDA 12.x (_not_ in 1.9.0, but in a refresh)

## Library updates

_in progress_ items

- [x] OpenBLAS 0.3.23*
- [x] TensorFlow / Keras 2.12*
- [ ] TensorFlow Serving 2.12
- [x] PyTorch 2*
- [x] PyTorch patch for P10 to remove vsx suffix from sleef calls
- [x] _PyTorch Lightning TBD_
- [x] PyArrow 11*
- [x] _Dali 1.25*_
- [x] ONNX 1.13*
- [x] ONNX Runtime "Family"* TBD
- [x] Horovod 0.28*
- [x] SnapML 1.13*
- [x] XGBoost 1.6 (for CPD)
- [x] XGBoost 1.7
- [x] Ray 2.4
- [x] _mamba 1.4*_
- [x] OpenCV 4.7*
- [x] Beam 2.46
- [x] LightGBM 3.3.2*
- [x] LightGBM 3.3.5
- [x] DeepSpeed 0.8
- [x] prophet 1.1.2
- [x] _orbit-ml 1.1.4_
- [x] cmdstan 2.31.0
- [x] cmdstanpy 1.1.0
- [x] Huggingface Datasets 2.9
- [x] Huggingface tokenizers 0.13.3
- [x] tensorflow-io 0.32
- [x] _or-tools 9.4_
- [ ] Relax strict pins for dependencies from Anaconda where-ever possible. 
- [x] Relax or remove libarchive pin. 
-  ~~Allow libxml2 v2.9 and 2.10 in uwsgi.~~
- [x] relax leveldb pin to 1.23.*
- [x] restrict scikit-learn to 1.1.*
- [x] use single version of numactl for all platforms - v2.0.16. 
- [x] stop building uwsgi as its available on Anaconda
- [ ] tokenizers for fips
- [x] ffmpeg with disabled codes for non-fips 
- [ ] ffmpeg with disabled codecs and openssl for fips

## New Libraries (Candidates)
- [x] _jax_  (Not on P10)
-  tslearn  Not included in 1.9

## Miscellaneous
- [x] Remove wheel pins from TF and TB recipes. Check other recipes too
- [ ] Fix feedstock tests for TF, Pytorch, xgboost, etc.
-  ~~Port protobuf changes from Open-CE 1.7.5.~~
- [x] Port setuptools and wheels pin changes from 1.7.5 into opence

**Comment by MorenoLaQuatra** [comment]
It would be possible to also add other libraries? I'm having problem installing `torchaudio` from source. Given that torchtext and torchvision are already available it should be good to have the audio library also.

**Comment by alexlang74** [comment]
Hi @MorenoLaQuatra , 
please open a separate issue, type "feedstock request". We'll check where it fits in, maybe in a fixpack of 1.9...
