### ISSUE TITLE
[FEEDSTOCK REQUEST] Cuda12

### ISSUE THREAD

**Issue by kwwrigh** [open-ce/open-ce#777]
**Describe the package you'd like added**

I would like to have Cuda12 for power added

**Describe how this package fits in with the project**

It will add functionality  needed 

**Additional context**

**Comment by cdeepali** [comment]
Thank you for raising this request.  We will look into adding it into OpenCE but I think it will not happen immediately. 

Do you need it for a specific framework?

**Comment by alexlang74** [comment]
Support for CUDA 12.1 is currently targeted for OpenCE 1.9.1. We will focus on testing PyTorch and Tensorflow with that CUDA version

**Comment by ntl-ibm** [comment]
Is this still on track for OpenCE 1.9.1?

**Comment by alexlang74** [comment]
Hi @ntl-ibm , 
we still target it for OpenCE 1.9.x. We're currently working through some higher-priority items for 1.9.1 (i.e., leftovers from 1.9.0). We're now looking at delivering CUDA 12 with 1.9.2, to not delay the 1.9.1 timeline...

**Comment by alexlang74** [comment]
Quick update: we started to evaluate CUDA 12.2. Depending on the outcome, this may go either into OpenCE 1.9.2 / 1.9.3 or OpenCE 1.10...

**Comment by ntl-ibm** [comment]
Hi,

Is this still on track for 1.10?

**Comment by alexlang74** [comment]
Hi @ntl-ibm , 
yes, we plan to support CUDA 12.2 with 1.10

**Comment by ntl-ibm** [comment]
Thanks, is there an estimated date when 1.10 will be available?

**Comment by alexlang74** [comment]
Delivered in 1.10 and 1.11
