### ISSUE TITLE
[FEEDSTOCK REQUEST] Additional packages for dependency resolution when using the POWER optimized version of Python

### ISSUE THREAD

**Issue by harmojd** [open-ce/open-ce#797]
Open-CE Team,

My name is Jesse Harmon and I collaborating with the POWER enablement and optimization team (Calvin Sze and Dave Marquardt.)

We are requesting the following packages/dependencies to be included in a future Open-CE/RocketCE release:
-- pyomo
-- numba
-- swifter
-- pandas

Our goal is to have a consistent https://anaconda.org/rocketce REPO for our "core heavy lifting" packages/dependencies to ease the pain of dependency resolution when using the POWER optimized version of Python.

You all have already included our other current "core heavy lifting" packages/dependencies and are very appreciative.

Thanks for all your help and support,
Jesse and Lenin

**Comment by alexlang74** [comment]
Hi Jesse, Hi Lenin,

the OpenCE team focuses on libraries that are not provided by the Anaconda default channel. `numba` and `pandas` are, and we have various clients using them together with the OpenCE libraries without an issue. Hence, we have _no plan_ to add these packages to OpenCE.

I hear your pain regarding the dependency resolution. Unfortunately, we can't address _all_ such problems by increasing the scope of OpenCE. Even today, a substantial amount of our work goes into ensuring that our libraries install together. We have to pick our battles here...

**Comment by alexlang74** [comment]
Regarding `swifter`:
- It's supported by a single person
- Its last release was over a year ago
- The commit activity shows that the project is essentially dormant: https://github.com/jmcarpenter2/swifter/graphs/commit-activity

Unfortunately, these are "knock-out" items for getting these added to OpenCE. There is too much risk that we don't get any support from the open source project when we run into issues. Also, it's not clear whether swifter will continue to be supported for more recent versions of pandas (e.g., 2.0 that just got released).

Have you tried `dask` or `ray` for your parallelization needs ? They will require code changes, but both are fairly mature libraries, with a large support community. And we include `ray` in OpenCE. There is also https://github.com/nalepae/pandarallel , which is _slightly_ more active than swifter...

**Comment by alexlang74** [comment]
Regarding `pyomo`: 

This looks like a healthy open source project that fits OpenCE. It _is_ available via pip install, and works on Power. What would be the advantage for you to have it provided via OpenCE ?

**Comment by alexlang74** [comment]
Hi @harmojd , 

can we close this, or is there still a package you'd request?

**Comment by alexlang74** [comment]
Closing now. Please reopen if still relevant
