### ISSUE TITLE
OpenCE 1.10 Release contents

### ISSUE THREAD

**Issue by npanpaliya** [open-ce/open-ce#857]
## Python versions

- Python 3.9
- Python 3.10
- Python 3.11

## CUDA versions

- Plan: DROP support for CUDA 11.2 
- CUDA 11.8 
- CUDA 12.2

## Library updates

_in progress_ items

- [x] OpenBLAS 0.3.*
- [x] TensorFlow / Keras 2.13.*
- [x] _TensorFlow Serving 2.13_
- [x] PyTorch 2.0.*
- [x] Pytorch P10 changes with `mcpu=power9` and `-mtune=power10`
- [x] _PyTorch Lightning 2.0.6_
- [x] PyArrow 12
- [x] _Dali 1.28*_
- [x] ONNX 1.14.*
- [x] _ONNX Runtime "Family" 1.15.*_
- [x] Horovod 0.28.1
- [x] SnapML 1.14.*
- [x] XGBoost 1.7
- [ ] _Ray 2.6.*_
- [x] _mamba 1.49_
- [x] OpenCV 4.8.* with CUDA support
- [x] _Beam 2.49_
- [x] LightGBM 3.3.5
- [x] LightGBM 4.0
- [x] DeepSpeed 0.10.0
- [ ] DeepSpeed ops
- [x] prophet 1.1.4
- [x] orbit-ml 1.1.4
- [x] cmdstan 2.31.0
- [x] cmdstanpy 1.1.0
- [x] Huggingface Datasets 2.14.*
- [x] _Huggingface tokenizers 0.13.3_
- [x] tensorflow-io 0.33
- [x] or-tools 9.6
- [x] scipy 1.11
- [x] numpy 1.24.3 (for P10)
- [x] _openssl 3.* support_ - Build all packages with openssl 3
- [ ] _openssl 3.* for FIPS_
- [ ] cryptography 41 (for FIPS)

## New Libraries (Candidates)
Nothing so far

## Power10 only libraries
Build all the libraries with `-mcpu=power10` and `-mtune=power10` on a Power10 system.

 ## Miscellaneous
- [ ] Include any findings from the performance test
- [ ] Deepspeed issue
- [ ] Support OSU team
- [ ] Support ORNL team

**Comment by rolweber** [comment]
I recommend to move `cryptography` out of the Open CE release content. For general use, the package is available from Anaconda. For FIPS support, it will be beneficial to have only FIPS-relevant packages in a supplemental release, which can be updated and built with a much faster turnaround time, on x86 only.

For `openssl`, the Open CE release must be compatible with version 3, but the package itself can be part of the supplemental release. Anaconda has some builds of openssl 3 on all platforms.
