### ISSUE TITLE
Verify that system CUDA version matches cudatoolkit version

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#88]
The build_feedstock script should check that the version of CUDA installed matches the version that is provided by the cudatoolkit version. If it doesn't match, an error should be thrown and the build should fail.

It should also check that CUDA_HOME is set. If it isn't set, it can be set with a default value.

It should also check that CUDA_HOME matches the `nvcc` that is in the system PATH.

**Comment by dncliss** [comment]
Nothing much on my plate at the moment while waiting on some older PRs to be reviewed -- I'll self-assign and take look at this one.

**Comment by dncliss** [comment]
This one got set aside 3 months ago.  Re-engaged; Killed earlier outdated PR and started fresh.

**Comment by dncliss** [comment]
The earlier attempt to do this item remains available, in the PR mentioned above.  But I never finished it off and I think it's best that I put it back into the backlog pool (either for someone else to pick up, or to dispose if no longer desired.)

**Comment by alexlang74** [comment]
No intent to address
