### ISSUE TITLE
[FEEDSTOCK REQUEST] bitsandbytes

### ISSUE THREAD

**Issue by madmax-codewarrior-0** [open-ce/open-ce#890]
**Describe the package you'd like added**
bitsandbytes - 8-bit CUDA functions for PyTorch

Source and more info: https://github.com/TimDettmers/bitsandbytes

**Describe how this package fits in with the project**
CUDA wrapper with optimizations, and also allows use of system memory on GPUs.

**Additional context**
\* submitted on behalf from Open-CE users at US Bank

**Comment by cdeepali** [comment]
covered in https://github.com/open-ce/open-ce/pull/1254
