### ISSUE TITLE
[BUG] 181 - HTTP errors observed with OpenCE 181

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#922]
Cloning into bare repository '/opt/conda/conda-bld/git_cache/github.com/tensorflow/tensorflow.git'...
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
fatal: expected 'packfile'
Cloning into bare repository '/opt/conda/conda-bld/git_cache/github.com/tensorflow/tensorflow.git'...
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
fatal: expected 'packfile'
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/git', 'clone', '--mirror', 'https://github.com/tensorflow/tensorflow.git', '/opt/conda/conda-bld/git_cache/github.com/tensorflow/tensorflow.git']' returned non-zero exit status 128.

**Comment by madmax-codewarrior-0** [comment]
Also seeing this in 1.7.10, with the proper workaround in place (`git config --global http.version HTTP/1.1` + `git config --global http.postBuffer 157286400`)

**Comment by madmax-codewarrior-0** [comment]
> Also seeing this in 1.7.10, with the proper workaround in place (`git config --global http.version HTTP/1.1` + `git config --global http.postBuffer 157286400`)

No longer seeing this! (Resolved)
