### ISSUE TITLE
Update PyTorch to v2.1.0

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#941]
Update PyTorch and dependencies to v2.1.*

- [ ] Update AV to v11.0
- [ ] Update PyTorch to v2.1.0
- [x] Update sentencepiece to v0.1.99
- [x] Update torchtext to v0.16.0
- [x] Update torchvision to v0.16.0
- [x] Update torchdata to v0.7.0

**Comment by cdeepali** [comment]
Pytorch v2.1.1 is likely to be tagged soon.

**Comment by cdeepali** [comment]
PyTorch v2.1.1 is tagged. So we can target the following versions:

- [ ]  Update AV to v11.0
- [ ]  Update PyTorch to v2.1.1
- [X]  Update sentencepiece to v0.1.99
- [ ]  Update torchtext to v0.16.1
- [ ]  Update torchvision to v0.16.1
- [ ]  Update torchdata to v0.7.1

**Comment by cdeepali** [comment]
As we see that there is a difference in the ffmpeg versions needed for torchvison and AV, we have decided to keep AV at v10.0.0.

**Comment by Aman-Surkar** [comment]
Refreshed PyTorch to v2.1.1
Refreshed Sentencepiece to v0.1.99
Refreshed Torchtext to v0.16.1
Refreshed Torchvision to v0.16.1
Refreshed Torchdata to v0.7.1

**Comment by Aman-Surkar** [comment]
- [ ] Refreshed PyTorch to v2.1.2

- [ ] Refreshed Sentencepiece to v0.1.99

- [ ] Refreshed Torchtext to v0.16.1

- [ ] Refreshed Torchvision to v0.16.1

- [ ] Refreshed Torchdata to v0.7.1

**Comment by Aman-Surkar** [comment]
Please refer: https://github.com/open-ce/pytorch-feedstock/pull/119
