### ISSUE TITLE
Use some more dependencies of arrow from defaults channel for s390x

### ISSUE THREAD

**Issue by ravigumm** [open-ce/open-ce#951]
As more packages are available in defaults channel for as390x now, we can remove these 3 feedstocks' builds in arrow-env.yaml and make use of these packages from the defaults channel.
https://github.com/open-ce/open-ce/blob/main/envs/arrow-env.yaml#L15-L24
boost-cpp, libevent, thrift-cpp

**Comment by ravigumm** [comment]
CC: @cdeepali , @alexlang74

**Comment by cdeepali** [comment]
Sure @ravigumm, we will take this into consideration for future OpenCE releases.

**Comment by Aman-Surkar** [comment]
Hi @ravigumm, I have removed these boost-cpp, libevent, thrift-cpp feedstocks from arrow-env as per your suggestion. PR for the same: https://github.com/open-ce/open-ce/pull/1046

**Comment by cdeepali** [comment]
https://github.com/open-ce/open-ce/pull/1046

**Comment by cdeepali** [comment]
@Aman-Surkar, even glog, rapidjson and gflags are now available on Anaconda, so please remove them too.

**Comment by ravigumm** [comment]
pyarrow is added to defaults conda channel recently. So many of the dependencies could be available. Only thing to be looked in to is if the versions of those dependent packages are fine for pyarrow in open-ce release 1.11 or not.

**Comment by Aman-Surkar** [comment]
Removed `rapidjson, gflags, glog` from arrow-env as now available on Anaconda channel for s390x.
