### ISSUE TITLE
Verify that tokenizers v0.13.3 from Anaconda works with 1.9.4 packages. 

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#993]
Install tokenizers v0.13.3 from Anaconda on 194 env and verify that there are no conflicts.

**Comment by SaiSrivatsa2001** [comment]
1 . i have created env using 194-conda env file which present on GSA
2 . i have searched tokenizers using conda search , it gives
tokenizers                    0.13.3 py310h3d4f45a_0  pkgs/main
3. conda install tokenizers=0.13.3-py310h3d4f45a_0
4. above shows its already installed  ,
5. so we removed the tokenizers from env , while removing it transformers also listed as removed
6. re installed the tokenizers=0.13.3-py310h3d4f45a_0

**Comment by SaiSrivatsa2001** [comment]
two checks : 
1. import tokenizers; import transformers;
2. pip check 

- ```
deepspeed 0.8.3+f1e4fb0b8 requires ninja, which is not installed.
multiprocess 0.70.12.2 has requirement dill>=0.3.4, but you have dill 0.3.1.1.
lightning-bolts 0.6.0.post1 has requirement lightning-utilities==0.7.1, but you have lightning-utilities 0.8.0.
lightning-app 2.0.1 has requirement fastapi<0.89.0, but you have fastapi 0.95.2.
```

these are worked and pip check issues are known .

**Comment by SaiSrivatsa2001** [comment]
Done
